const LINKEDIN_SOURCE = Object.freeze({
  title: 'Optimizing your LinkedIn profile: an international guide',
  author: 'Nicole Barra',
  url: 'https://www.linkedin.com/pulse/optimizing-your-linkedin-profile-international-guide-nicole-barra--ujebf/',
});
const HARVARD_RESUME_SOURCE = Object.freeze({
  title: 'Create a Resume or Cover Letter',
  author: 'Harvard FAS Mignone Center for Career Success',
  url: 'https://careerservices.fas.harvard.edu/resources/hes-create-impactful-resumes-and-cover-letters/',
});
const DOL_RESUME_SOURCE = Object.freeze({
  title: 'Resume Essentials Participant Guide',
  author: 'U.S. Department of Labor',
  url: 'https://www.dol.gov/sites/dolgov/files/VETS/files/ResumeEssentials_PG_Interactive_Feb2026.pdf',
});
const CAREER_SEARCH_SOURCE = Object.freeze({
  title: 'Job Search',
  author: 'CareerOneStop, U.S. Department of Labor',
  url: 'https://www.careeronestop.org/JobSearch/job-search.aspx',
});
const DOL_INTERVIEW_SOURCE = Object.freeze({
  title: 'Interview Tips',
  author: 'U.S. Department of Labor',
  url: 'https://www.dol.gov/general/jobs/interview-tips?lang=en',
});
const DOL_INTERVIEW_GUIDE = Object.freeze({
  title: 'Interview Skills Participant Guide',
  author: 'U.S. Department of Labor',
  url: 'https://www.dol.gov/sites/dolgov/files/VETS/files/InterviewSkills_PG_Interactive_Feb2026.pdf',
});

const PILLAR_LABEL = Object.freeze({
  linkedin: 'LINKEDIN',
  resume: 'CURRÍCULO',
  search: 'BUSCA DE VAGAS',
  application: 'CANDIDATURA',
  interview: 'ENTREVISTA',
});

function guide({
  id, pillar, title, promise, context, action, actionTitle = 'Faça assim', before, after,
  second, secondTitle = 'Ajuste que faz diferença', checklist, cta, sources,
}) {
  return Object.freeze({
    id,
    version: '1',
    pillar,
    title,
    promise,
    slides: Object.freeze([
      Object.freeze({ kind: 'cover', title, body: promise }),
      Object.freeze({ kind: 'context', title: 'Por que isso importa', body: context }),
      Object.freeze({ kind: 'action', title: actionTitle, body: action }),
      Object.freeze({ kind: 'example', title: 'Antes e depois', before, after }),
      Object.freeze({ kind: 'action', title: secondTitle, body: second }),
      Object.freeze({ kind: 'checklist', title: 'Checklist rápido', items: Object.freeze(checklist) }),
      Object.freeze({ kind: 'cta', title: 'Aplique hoje', body: cta }),
    ]),
    story: Object.freeze({
      eyebrow: PILLAR_LABEL[pillar],
      title,
      body: `${promise} Veja o passo a passo completo no feed.`,
    }),
    caption: Object.freeze({
      hook: promise,
      action: `${cta} Salve este guia para revisar antes da próxima candidatura.`,
    }),
    hashtags: Object.freeze(['OpeningsDev', 'CarreiraTech', PILLAR_LABEL[pillar].replaceAll(' ', '')]),
    sources: Object.freeze(sources),
    minRepeatDays: 84,
  });
}

export const EDITORIAL_CATALOG = Object.freeze([
  guide({
    id: 'linkedin-headline-clara', pillar: 'linkedin', title: 'Seu título do LinkedIn precisa dizer o que você entrega',
    promise: 'Troque palavras soltas por uma proposta profissional clara e encontrável.',
    context: 'O título aparece em buscas, comentários e convites. Ele precisa combinar termos usados por recrutadores com uma especialidade real.',
    action: 'Use a estrutura: função ou especialidade + tecnologia ou setor + impacto que você gera. Priorize os termos da vaga que combinam com sua experiência.',
    before: 'Desenvolvedor | Em busca de oportunidades',
    after: 'Backend Developer | Node.js e APIs | Produtos financeiros escaláveis',
    second: 'Evite uma lista interminável de ferramentas. Escolha duas ou três palavras-chave fortes e uma entrega que dê contexto.',
    checklist: ['Função específica', 'Duas palavras-chave relevantes', 'Impacto ou setor', 'Sem clichês vazios'],
    cta: 'Reescreva seu título em uma frase e compare com três vagas que você quer.', sources: [LINKEDIN_SOURCE],
  }),
  guide({
    id: 'linkedin-idioma-do-perfil', pillar: 'linkedin', title: 'Configure o idioma do LinkedIn para o mercado que você quer',
    promise: 'Faça recrutadores encontrarem e entenderem seu perfil sem depender de tradução improvisada.',
    context: 'Idioma e mercado-alvo precisam conversar. Um perfil para vagas internacionais deve apresentar função, resultados e termos técnicos na língua usada nas oportunidades.',
    action: 'Defina um idioma principal coerente com sua busca. Se atuar em dois mercados, crie a versão secundária do perfil e mantenha fatos e datas iguais.',
    before: 'Título em inglês, Sobre em português e experiências misturadas',
    after: 'Versão principal consistente e segunda versão completa para outro mercado',
    second: 'Não traduza nomes oficiais de empresas ou produtos. Traduza o contexto, a responsabilidade e o resultado para o leitor.',
    checklist: ['Idioma alinhado às vagas', 'Seções consistentes', 'Termos técnicos naturais', 'Datas iguais nas versões'],
    cta: 'Abra cinco vagas-alvo e confirme qual idioma domina as descrições.', sources: [LINKEDIN_SOURCE],
  }),
  guide({
    id: 'linkedin-sobre-que-posiciona', pillar: 'linkedin', title: 'Escreva um Sobre que conecta experiência, foco e prova',
    promise: 'Transforme sua apresentação em um resumo que ajuda o recrutador a entender seu encaixe.',
    context: 'O Sobre não deve repetir o currículo inteiro. Ele organiza a leitura: quem você é, quais problemas resolve e quais evidências sustentam isso.',
    action: 'Comece com função e foco. Depois cite duas forças, uma realização concreta e o tipo de desafio que busca. Escreva em primeira pessoa.',
    before: 'Profissional apaixonado por tecnologia e novos desafios.',
    after: 'Engenheiro de dados focado em pipelines confiáveis. Reduzi em 38% o tempo de processamento de uma plataforma de pagamentos.',
    second: 'Use parágrafos curtos e inclua palavras-chave apenas onde descrevem experiência verdadeira. Feche com uma direção profissional específica.',
    checklist: ['Função e foco', 'Duas competências', 'Uma prova concreta', 'Próximo desafio claro'],
    cta: 'Escreva quatro frases seguindo essa ordem e corte tudo que não adiciona evidência.', sources: [LINKEDIN_SOURCE],
  }),
  guide({
    id: 'linkedin-titulo-de-experiencia', pillar: 'linkedin', title: 'Use títulos de experiência que recrutadores reconhecem',
    promise: 'Dê contexto ao cargo sem inventar senioridade nem esconder sua especialidade.',
    context: 'Títulos internos podem ser pouco conhecidos. Um termo reconhecível melhora a leitura e a busca, desde que continue fiel ao cargo exercido.',
    action: 'Mantenha o título oficial e acrescente a especialidade entre parênteses quando necessário. Explique escopo e nível nas atividades.',
    before: 'Ninja II',
    after: 'Software Engineer II (Backend)',
    second: 'Não promova a si mesmo no título. Demonstre senioridade por decisões, complexidade, autonomia e resultados descritos.',
    checklist: ['Título fiel', 'Especialidade explícita', 'Senioridade comprovável', 'Termos reconhecíveis'],
    cta: 'Revise os títulos internos que alguém de fora da empresa talvez não entenda.', sources: [LINKEDIN_SOURCE],
  }),
  guide({
    id: 'linkedin-resultados-na-experiencia', pillar: 'linkedin', title: 'Troque tarefas por resultados nas experiências do LinkedIn',
    promise: 'Mostre como seu trabalho mudou produto, processo, receita, custo ou qualidade.',
    context: 'Uma lista de obrigações diz o que o cargo esperava. Resultados mostram o que você realmente entregou e tornam sua experiência mais crível.',
    action: 'Monte cada ponto com ação + contexto + resultado. Quando não houver métrica financeira, use escala, tempo, adoção, qualidade ou redução de risco.',
    before: 'Responsável por desenvolver APIs e corrigir bugs.',
    after: 'Redesenhei 6 APIs críticas e reduzi falhas de integração em 31% em quatro meses.',
    second: 'Use verbos específicos e explique a base da métrica. Uma estimativa honesta com contexto vale mais que um número impressionante sem origem.',
    checklist: ['Verbo de ação', 'Escopo definido', 'Resultado observado', 'Métrica com contexto'],
    cta: 'Reescreva hoje o primeiro ponto da sua experiência mais recente.', sources: [LINKEDIN_SOURCE],
  }),
  guide({
    id: 'linkedin-skills-encontraveis', pillar: 'linkedin', title: 'Organize competências do LinkedIn para ser encontrado',
    promise: 'Faça sua lista de skills refletir o trabalho que você quer e as provas que já tem.',
    context: 'Competências ajudam na busca, mas uma lista genérica dilui seu posicionamento. As principais precisam combinar com experiências e vagas-alvo.',
    action: 'Levante termos recorrentes em dez vagas compatíveis. Selecione apenas os que você domina e conecte os mais importantes às experiências correspondentes.',
    before: '50 competências misturando Office, liderança, Java e marketing',
    after: 'Competências prioritárias coerentes com Backend, APIs e cloud',
    second: 'Ordene as competências principais pela função desejada, não pela ordem em que foram adicionadas. Remova itens desatualizados ou sem relevância.',
    checklist: ['Termos das vagas-alvo', 'Domínio verdadeiro', 'Ligação com experiências', 'Prioridades atualizadas'],
    cta: 'Compare suas dez primeiras competências com os requisitos de três vagas.', sources: [LINKEDIN_SOURCE],
  }),
  guide({
    id: 'linkedin-provas-em-destaque', pillar: 'linkedin', title: 'Use a seção Destaques como vitrine de provas',
    promise: 'Leve o recrutador direto a projetos, textos e entregas que sustentam seu perfil.',
    context: 'Dizer que sabe é diferente de mostrar. A seção Destaques reduz o caminho entre uma afirmação profissional e a evidência.',
    action: 'Escolha de dois a quatro materiais diretamente ligados ao seu foco: case, repositório explicado, artigo, palestra, demo ou portfólio.',
    before: 'Links antigos sem título ou explicação',
    after: 'Case: migração reduziu custo de nuvem em 24% — contexto e decisões',
    second: 'Dê a cada item um título que explique o valor. Remova materiais quebrados, confidenciais, sem autoria clara ou fora do seu objetivo.',
    checklist: ['Prova relevante', 'Título explicativo', 'Link funcionando', 'Sem dado confidencial'],
    cta: 'Escolha uma entrega real e escreva uma linha explicando por que ela importa.', sources: [LINKEDIN_SOURCE],
  }),
  guide({
    id: 'linkedin-recomendacoes-que-comprovam', pillar: 'linkedin', title: 'Peça recomendações que tragam evidência',
    promise: 'Troque elogios genéricos por relatos que confirmam como é trabalhar com você.',
    context: 'Recomendações aumentam credibilidade quando descrevem relação, situação e contribuição. “Ótimo profissional” sozinho acrescenta pouco.',
    action: 'Peça a alguém que acompanhou seu trabalho. Lembre o projeto, a responsabilidade e o resultado para facilitar uma recomendação específica.',
    before: 'Você pode escrever uma recomendação para mim?',
    after: 'Você poderia comentar nossa migração, meu papel na decisão e o impacto no time?',
    second: 'Busque perspectivas diferentes: liderança, par e parceiro de outra área. Não escreva o texto final pela pessoa nem combine elogios falsos.',
    checklist: ['Relação de trabalho real', 'Projeto lembrado', 'Contribuição específica', 'Perspectivas variadas'],
    cta: 'Escolha uma pessoa e envie um pedido curto com contexto suficiente.', sources: [LINKEDIN_SOURCE],
  }),
  guide({
    id: 'linkedin-contexto-remoto', pillar: 'linkedin', title: 'Mostre no LinkedIn que você sabe trabalhar remotamente',
    promise: 'Comprove colaboração distribuída em vez de apenas escrever “remote”.',
    context: 'Trabalho remoto exige comunicação, autonomia e coordenação entre horários. Essas competências ficam mais fortes quando aparecem em situações reais.',
    action: 'Nas experiências, cite times distribuídos, fusos, rituais assíncronos, documentação e como você reduziu dependências ou ruído.',
    before: 'Experiência com trabalho remoto.',
    after: 'Coordenei releases assíncronos entre Brasil e Europa, reduzindo bloqueios de entrega em 20%.',
    second: 'Inclua sua localização e preferência de trabalho com clareza. Não prometa disponibilidade de horário que você não consegue sustentar.',
    checklist: ['Time distribuído', 'Prática de comunicação', 'Resultado observado', 'Disponibilidade realista'],
    cta: 'Adicione uma prova de colaboração remota à experiência mais relevante.', sources: [LINKEDIN_SOURCE],
  }),
  guide({
    id: 'linkedin-contato-profissional', pillar: 'linkedin', title: 'Facilite o contato sem expor informação demais',
    promise: 'Deixe um caminho profissional claro para quem encontrou seu perfil.',
    context: 'Um bom perfil perde oportunidades se o contato estiver escondido ou desatualizado. Ao mesmo tempo, privacidade continua sendo parte da estratégia.',
    action: 'Revise e-mail profissional, portfólio, localização e URL personalizada. Disponibilize apenas os dados necessários para a conversa inicial.',
    before: 'E-mail antigo e portfólio com link quebrado',
    after: 'E-mail profissional, URL limpa e portfólio funcional',
    second: 'Teste os links em uma janela anônima. Evite endereço residencial, documentos pessoais ou telefone aberto sem necessidade.',
    checklist: ['E-mail acessível', 'URL personalizada', 'Portfólio testado', 'Privacidade revisada'],
    cta: 'Abra seu perfil como visitante e teste cada caminho de contato.', sources: [LINKEDIN_SOURCE],
  }),
  guide({
    id: 'linkedin-atividade-estrategica', pillar: 'linkedin', title: 'Use sua atividade no LinkedIn para reforçar autoridade',
    promise: 'Faça comentários e posts trabalharem a favor do posicionamento do seu perfil.',
    context: 'Sua atividade também é parte da impressão profissional. Participação útil mostra repertório, clareza e interesse genuíno pelo campo.',
    action: 'Comente experiências, dados ou perguntas específicas em temas do seu foco. Publique aprendizados com contexto, decisão e resultado.',
    before: 'Parabéns! Conteúdo incrível.',
    after: 'Esse trade-off apareceu no nosso checkout; medir o erro por etapa mudou a prioridade do time.',
    second: 'Prefira consistência a volume. Duas contribuições úteis por semana são melhores que comentários genéricos em dezenas de posts.',
    checklist: ['Tema alinhado ao foco', 'Contribuição concreta', 'Tom profissional', 'Frequência sustentável'],
    cta: 'Faça hoje um comentário que acrescente exemplo, pergunta ou contraponto útil.', sources: [LINKEDIN_SOURCE],
  }),
  guide({
    id: 'linkedin-privacidade-open-to-work', pillar: 'linkedin', title: 'Configure o Open to Work com intenção e privacidade',
    promise: 'Sinalize o que procura sem transformar o perfil em uma mensagem vaga.',
    context: 'Preferências bem configuradas ajudam a filtrar oportunidades. Visibilidade e privacidade devem refletir seu momento profissional.',
    action: 'Defina cargos, localidades, formatos de trabalho e disponibilidade reais. Escolha conscientemente quem verá o sinal de busca.',
    before: 'Aberto a qualquer oportunidade em qualquer lugar',
    after: 'Backend Engineer, remoto no Brasil ou híbrido em São Paulo, início em 30 dias',
    second: 'Revise periodicamente as configurações e o impacto no emprego atual. Nenhuma opção de plataforma substitui uma busca ativa e direcionada.',
    checklist: ['Cargos definidos', 'Localidade realista', 'Formato preferido', 'Visibilidade consciente'],
    cta: 'Abra suas preferências e remova opções que você não aceitaria de verdade.', sources: [LINKEDIN_SOURCE],
  }),

  guide({
    id: 'resume-resumo-direto', pillar: 'resume', title: 'Escreva um resumo de currículo que chega ao ponto',
    promise: 'Apresente função, especialidade e evidência em poucas linhas.',
    context: 'O topo do currículo precisa orientar a leitura. Objetivos genéricos ocupam espaço sem explicar por que você combina com a vaga.',
    action: 'Use três linhas: identidade profissional, competências centrais e uma prova relacionada ao cargo. Ajuste os termos para cada vaga.',
    before: 'Busco uma oportunidade para crescer e contribuir com a empresa.',
    after: 'Product Designer com 5 anos em SaaS B2B; redesenho de onboarding elevou ativação em 18%.',
    second: 'Evite adjetivos sem prova. Se você está no início, troque anos de experiência por projeto relevante, domínio técnico e contexto.',
    checklist: ['Cargo-alvo', 'Especialidade', 'Evidência concreta', 'Até quatro linhas'],
    cta: 'Corte a frase que serviria para qualquer candidato e inclua uma prova sua.', sources: [HARVARD_RESUME_SOURCE, DOL_RESUME_SOURCE],
  }),
  guide({
    id: 'resume-bullets-de-impacto', pillar: 'resume', title: 'Transforme responsabilidades em bullets de impacto',
    promise: 'Mostre ação, contexto e efeito em cada ponto do currículo.',
    context: 'Responsabilidades descrevem o cargo; realizações diferenciam o candidato. Cada bullet deve tornar uma contribuição fácil de escanear.',
    action: 'Comece com verbo forte, diga o que mudou e encerre com resultado ou escala. Um bullet deve carregar uma ideia principal.',
    before: 'Responsável por testes do sistema.',
    after: 'Automatizei 140 testes críticos e reduzi regressões em produção em 27%.',
    second: 'Ordene os bullets por relevância para a vaga, não por cronologia da tarefa. Mantenha de três a cinco pontos fortes por experiência.',
    checklist: ['Verbo específico', 'Uma ideia por bullet', 'Resultado ou escala', 'Ordem por relevância'],
    cta: 'Reescreva o bullet mais genérico da sua experiência recente.', sources: [HARVARD_RESUME_SOURCE, DOL_RESUME_SOURCE],
  }),
  guide({
    id: 'resume-metricas-com-contexto', pillar: 'resume', title: 'Use métricas no currículo sem inventar precisão',
    promise: 'Dê dimensão às entregas com números honestos e explicados.',
    context: 'Métricas ajudam o leitor a avaliar escala e impacto. Sem contexto, porém, o número pode parecer decorativo ou pouco confiável.',
    action: 'Procure volume, tempo, adoção, qualidade, custo, receita ou risco. Explique a comparação: antes e depois, período ou universo medido.',
    before: 'Melhorei bastante a performance da aplicação.',
    after: 'Reduzi o p95 de 1,8 s para 900 ms em três rotas usadas por 60 mil clientes.',
    second: 'Se o dado exato for confidencial, use percentual, faixa ou escala aproximada e sinalize o contexto sem revelar informação protegida.',
    checklist: ['Métrica verificável', 'Base de comparação', 'Período ou escala', 'Sem dado confidencial'],
    cta: 'Liste três entregas e associe a cada uma um indicador que você consegue defender.', sources: [HARVARD_RESUME_SOURCE, DOL_RESUME_SOURCE],
  }),
  guide({
    id: 'resume-formato-ats', pillar: 'resume', title: 'Deixe seu currículo fácil de ler por pessoas e sistemas',
    promise: 'Use uma estrutura simples para evitar que informação importante se perca.',
    context: 'Layouts complexos podem prejudicar leitura e extração de dados. Clareza visual também ajuda quem faz a primeira triagem rapidamente.',
    action: 'Prefira uma coluna, títulos convencionais, ordem cronológica reversa e texto selecionável. Use datas e cargos com formato consistente.',
    before: 'Duas colunas, barras de skill, ícones e informações dentro de imagens',
    after: 'Seções claras, texto real, hierarquia simples e datas consistentes',
    second: 'Exporte em PDF quando solicitado e confira se copiar e colar preserva a ordem. Siga o formato pedido no anúncio.',
    checklist: ['Uma coluna', 'Títulos convencionais', 'Texto selecionável', 'Arquivo solicitado'],
    cta: 'Copie o texto do PDF para um editor simples e veja se a ordem continua lógica.', sources: [HARVARD_RESUME_SOURCE, DOL_RESUME_SOURCE],
  }),
  guide({
    id: 'resume-curriculo-por-vaga', pillar: 'resume', title: 'Adapte o currículo para a vaga sem reescrever sua história',
    promise: 'Mude ênfase e ordem para tornar o encaixe evidente.',
    context: 'Um currículo único tende a destacar informação irrelevante. Adaptar não é inventar: é selecionar as provas mais úteis para aquela oportunidade.',
    action: 'Marque requisitos obrigatórios e preferenciais. Reordene resumo, competências e bullets para colocar evidências correspondentes primeiro.',
    before: 'Mesmo currículo enviado para frontend, dados e gestão',
    after: 'Versão que prioriza as experiências compatíveis com cada função',
    second: 'Use a linguagem da vaga quando ela descreve algo que você realmente fez. Não copie blocos inteiros nem inclua competência sem prova.',
    checklist: ['Requisitos marcados', 'Resumo ajustado', 'Provas priorizadas', 'Sem exagero'],
    cta: 'Antes do próximo envio, escolha os três requisitos que seu currículo precisa provar.', sources: [HARVARD_RESUME_SOURCE, DOL_RESUME_SOURCE],
  }),
  guide({
    id: 'resume-projetos-relevantes', pillar: 'resume', title: 'Use projetos para provar experiência relevante',
    promise: 'Dê peso a projetos pessoais, acadêmicos ou voluntários com contexto e resultado.',
    context: 'Projetos podem fechar lacunas de experiência quando demonstram decisões e habilidades próximas do trabalho desejado.',
    action: 'Inclua problema, seu papel, escolhas técnicas e resultado. Se houve equipe, deixe clara sua contribuição individual.',
    before: 'Projeto de e-commerce em React.',
    after: 'Criei checkout acessível em React; conduzi testes com 8 usuários e corrigi 12 barreiras de navegação.',
    second: 'Selecione poucos projetos fortes. Link só ajuda se estiver funcionando, tiver instruções claras e não expuser segredos.',
    checklist: ['Problema definido', 'Papel individual', 'Decisões explicadas', 'Resultado ou aprendizado'],
    cta: 'Escolha o projeto mais alinhado à vaga e reescreva sua descrição em três bullets.', sources: [HARVARD_RESUME_SOURCE, DOL_RESUME_SOURCE],
  }),
  guide({
    id: 'resume-portfolio-que-prova', pillar: 'resume', title: 'Conecte o currículo a um portfólio que prova seu trabalho',
    promise: 'Faça cada link levar a uma evidência clara, curta e acessível.',
    context: 'Um portfólio sem contexto transfere trabalho para o recrutador. O material precisa explicar problema, participação e raciocínio.',
    action: 'Para cada case, apresente cenário, restrições, decisões, contribuição e resultado. Mostre o suficiente para avaliar sem revelar material confidencial.',
    before: 'Galeria de telas sem explicação.',
    after: 'Case com problema, opções consideradas, decisão tomada e impacto medido.',
    second: 'Use URLs estáveis e títulos descritivos. Teste em celular e janela anônima para evitar acesso bloqueado.',
    checklist: ['Case com contexto', 'Autoria explícita', 'Decisão demonstrada', 'Link público testado'],
    cta: 'Abra seu principal case como visitante e anote o que não se entende em 30 segundos.', sources: [HARVARD_RESUME_SOURCE],
  }),
  guide({
    id: 'resume-revisao-final', pillar: 'resume', title: 'Faça uma revisão final que evita eliminações bobas',
    promise: 'Confira conteúdo, consistência e arquivo antes de enviar.',
    context: 'Erros pequenos podem gerar dúvida sobre atenção a detalhes. Uma rotina curta de revisão reduz risco sem travar a candidatura.',
    action: 'Leia o currículo fora do editor e depois em voz alta. Compare cargo, empresa e requisitos com o anúncio mais uma vez.',
    before: 'curriculo_final_agora-v3.pdf com link quebrado e data diferente',
    after: 'nome-sobrenome-cargo.pdf, datas consistentes e links verificados',
    second: 'Peça a alguém para responder: “qual é a principal força deste candidato?” Se a resposta não for clara, ajuste a hierarquia.',
    checklist: ['Ortografia revisada', 'Datas consistentes', 'Links testados', 'Nome de arquivo claro'],
    cta: 'Crie uma checklist fixa e só marque a candidatura como pronta depois dos quatro itens.', sources: [HARVARD_RESUME_SOURCE, DOL_RESUME_SOURCE],
  }),

  guide({
    id: 'search-busca-com-criterios', pillar: 'search', title: 'Defina critérios antes de abrir mais uma lista de vagas',
    promise: 'Concentre energia em oportunidades que você realmente aceitaria.',
    context: 'Buscar sem critérios aumenta volume e reduz qualidade. Limites claros ajudam a comparar vagas e personalizar candidaturas.',
    action: 'Defina função, senioridade, faixa, localidade, formato, setores e restrições. Separe o que é obrigatório do que é preferência.',
    before: 'Candidatar a qualquer vaga de tecnologia.',
    after: 'Backend pleno, remoto no Brasil, produto B2B e faixa mínima definida.',
    second: 'Revise os critérios com dados reais a cada duas semanas. Ajuste expectativas sem abandonar necessidades importantes.',
    checklist: ['Função-alvo', 'Faixa mínima', 'Local e formato', 'Restrições claras'],
    cta: 'Escreva seus quatro critérios obrigatórios antes da próxima busca.', sources: [CAREER_SEARCH_SOURCE],
  }),
  guide({
    id: 'search-alertas-uteis', pillar: 'search', title: 'Crie alertas de vagas que não viram ruído',
    promise: 'Receba oportunidades mais próximas do seu objetivo e aja cedo.',
    context: 'Alertas amplos lotam a caixa de entrada e escondem boas oportunidades. Combinações menores produzem sinais melhores.',
    action: 'Crie alertas separados por título, senioridade e local. Inclua sinônimos reais da função e exclua termos que geram falsos positivos quando possível.',
    before: 'Um alerta para “developer”.',
    after: 'Alertas para “backend engineer”, “node developer” e “API engineer”, remoto Brasil.',
    second: 'Reserve dois horários curtos para triagem. Desative alertas que não geram vagas compatíveis depois de uma semana.',
    checklist: ['Título específico', 'Sinônimos úteis', 'Local definido', 'Revisão semanal'],
    cta: 'Divida seu alerta mais amplo em duas buscas mais específicas.', sources: [CAREER_SEARCH_SOURCE],
  }),
  guide({
    id: 'search-fontes-alem-do-linkedin', pillar: 'search', title: 'Procure vagas além de uma única plataforma',
    promise: 'Amplie a cobertura sem transformar a busca em navegação infinita.',
    context: 'Empresas publicam em canais diferentes e algumas oportunidades aparecem primeiro em páginas próprias ou comunidades especializadas.',
    action: 'Monte uma lista curta com agregador, páginas de empresas-alvo, comunidades do setor e sua rede. Dê um horário para cada fonte.',
    before: 'Atualizar o mesmo feed várias vezes por dia.',
    after: 'Rotina com agregador, 15 empresas-alvo e duas comunidades relevantes.',
    second: 'Registre a origem de cada vaga. Depois de quatro semanas, mantenha as fontes que realmente geram conversas ou oportunidades compatíveis.',
    checklist: ['Agregador confiável', 'Empresas-alvo', 'Comunidades relevantes', 'Origem registrada'],
    cta: 'Escolha hoje cinco empresas e salve a página de carreiras de cada uma.', sources: [CAREER_SEARCH_SOURCE],
  }),
  guide({
    id: 'search-pesquisa-de-empresa', pillar: 'search', title: 'Pesquise a empresa antes de investir na candidatura',
    promise: 'Descubra contexto, riscos e argumentos para personalizar sua abordagem.',
    context: 'Uma vaga não mostra toda a realidade do trabalho. Pesquisa reduz surpresas e melhora currículo, mensagem e entrevista.',
    action: 'Verifique produto, clientes, modelo de negócio, notícias, liderança, cultura publicada e pessoas da área. Compare fontes.',
    before: 'A empresa parece legal e usa a tecnologia que eu gosto.',
    after: 'Entendo o produto, o estágio do negócio e dois desafios prováveis da equipe.',
    second: 'Separe fato, opinião e hipótese. Avaliações anônimas ajudam como sinal, mas não devem ser a única base da decisão.',
    checklist: ['Produto entendido', 'Momento do negócio', 'Equipe localizada', 'Riscos anotados'],
    cta: 'Antes de aplicar, escreva duas razões específicas para querer conversar com a empresa.', sources: [CAREER_SEARCH_SOURCE],
  }),
  guide({
    id: 'search-networking-intencional', pillar: 'search', title: 'Faça networking sem pedir emprego no primeiro contato',
    promise: 'Construa conversas úteis com contexto, respeito e reciprocidade.',
    context: 'Networking funciona melhor como troca de informação e relação profissional. Pedidos vagos transferem esforço para quem recebe.',
    action: 'Aproxime-se por interesse específico: trabalho publicado, experiência no setor ou decisão de carreira. Faça uma pergunta curta e pesquisada.',
    before: 'Oi, tem vaga aí? Pode me indicar?',
    after: 'Vi sua migração para dados. Que habilidade mais pesou na transição para esse time?',
    second: 'Respeite o tempo da pessoa e não cobre resposta. Compartilhe algo útil quando fizer sentido e mantenha a relação além da necessidade imediata.',
    checklist: ['Contexto específico', 'Pergunta curta', 'Sem pressão', 'Reciprocidade possível'],
    cta: 'Escolha uma pessoa do seu campo e escreva uma mensagem com contexto real.', sources: [CAREER_SEARCH_SOURCE],
  }),
  guide({
    id: 'search-rotina-semanal', pillar: 'search', title: 'Monte uma rotina de busca que você consegue sustentar',
    promise: 'Troque ansiedade e volume por um processo semanal mensurável.',
    context: 'Buscar emprego envolve descoberta, pesquisa, adaptação e acompanhamento. Fazer tudo ao mesmo tempo torna o progresso invisível.',
    action: 'Distribua blocos: buscar, selecionar, adaptar, conversar e acompanhar. Defina metas de qualidade, como candidaturas compatíveis e contatos relevantes.',
    before: 'Passar horas rolando vagas e enviar quando der.',
    after: '3 blocos de 45 minutos, 4 boas candidaturas e 2 conversas por semana.',
    second: 'Registre data, vaga, versão do currículo, contato e próximo passo. Revise o funil para descobrir onde precisa melhorar.',
    checklist: ['Blocos no calendário', 'Meta de qualidade', 'Acompanhamento registrado', 'Revisão semanal'],
    cta: 'Reserve agora três blocos curtos para a próxima semana.', sources: [CAREER_SEARCH_SOURCE],
  }),

  guide({
    id: 'application-leia-os-requisitos', pillar: 'application', title: 'Leia requisitos antes de decidir não se candidatar',
    promise: 'Separe o essencial do desejável e avalie seu encaixe com evidências.',
    context: 'Descrições misturam responsabilidades, requisitos obrigatórios e preferências. Tratar tudo como eliminatório exclui boas candidaturas.',
    action: 'Marque cada item como obrigatório, preferencial ou contexto. Para os essenciais, anote uma evidência; para lacunas, avalie impacto e aprendizado.',
    before: 'Não tenho 100% dos itens, então não vou aplicar.',
    after: 'Atendo aos essenciais e consigo explicar duas lacunas preferenciais.',
    second: 'Não ignore exigências legais, idioma necessário ou disponibilidade essencial. Use julgamento, não uma porcentagem mágica.',
    checklist: ['Obrigatórios separados', 'Preferenciais separados', 'Evidências anotadas', 'Lacunas avaliadas'],
    cta: 'Pegue uma vaga salva e classifique os requisitos em três grupos.', sources: [DOL_RESUME_SOURCE, CAREER_SEARCH_SOURCE],
  }),
  guide({
    id: 'application-evidencias-de-fit', pillar: 'application', title: 'Construa uma tabela de evidências antes de aplicar',
    promise: 'Conecte cada requisito importante a uma prova concreta da sua trajetória.',
    context: 'A candidatura fica mais forte quando currículo e respostas mostram correspondência explícita, sem obrigar o leitor a deduzir.',
    action: 'Crie duas colunas: requisito e evidência. Use projeto, resultado, decisão ou aprendizado real. Depois leve as melhores provas ao currículo.',
    before: 'Tenho perfil para a vaga.',
    after: 'Requisito: APIs. Evidência: 6 APIs redesenhadas, 31% menos falhas.',
    second: 'Se faltar prova, não invente. Decida entre destacar experiência transferível, produzir um projeto ou reconhecer uma lacuna.',
    checklist: ['Requisitos prioritários', 'Uma prova por requisito', 'Métrica quando existe', 'Lacunas honestas'],
    cta: 'Faça a tabela para os cinco requisitos mais importantes da próxima vaga.', sources: [DOL_RESUME_SOURCE],
  }),
  guide({
    id: 'application-respostas-concisas', pillar: 'application', title: 'Responda formulários de candidatura com clareza',
    promise: 'Use respostas curtas que entregam contexto, ação e resultado.',
    context: 'Perguntas abertas avaliam comunicação e aderência. Textos longos demais escondem a evidência; respostas vagas não permitem avaliação.',
    action: 'Responda primeiro à pergunta. Em seguida, traga um exemplo com situação, sua ação e resultado. Corte introduções genéricas.',
    before: 'Sempre fui apaixonado por desafios e acredito que posso contribuir muito.',
    after: 'Liderei a correção do checkout em 48 horas; a recuperação reduziu abandono em 9%.',
    second: 'Não reutilize a mesma resposta sem revisar. Confirme limite, idioma e se cada frase ajuda a comprovar o que foi perguntado.',
    checklist: ['Pergunta respondida', 'Exemplo específico', 'Ação individual', 'Resultado claro'],
    cta: 'Revise sua última resposta e mova a evidência para a primeira metade.', sources: [DOL_RESUME_SOURCE],
  }),
  guide({
    id: 'application-follow-up-profissional', pillar: 'application', title: 'Faça follow-up sem pressionar o recrutador',
    promise: 'Reforce interesse e contexto com uma mensagem curta e útil.',
    context: 'Um acompanhamento pode facilitar a retomada da conversa. Mensagens frequentes ou sem informação nova tendem a criar ruído.',
    action: 'Espere o prazo informado. Sem prazo, use alguns dias úteis. Identifique vaga, data, interesse específico e disponibilidade para complementar dados.',
    before: 'Oi, alguma novidade? Estou aguardando urgente.',
    after: 'Olá, enviei minha candidatura para Backend em 2/9. O desafio de APIs distribuídas me interessa; sigo disponível.',
    second: 'Envie uma vez pelo canal adequado. Se não houver resposta, continue outras oportunidades em vez de insistir repetidamente.',
    checklist: ['Prazo respeitado', 'Vaga identificada', 'Interesse específico', 'Tom sem cobrança'],
    cta: 'Prepare um modelo de quatro linhas e personalize o motivo de interesse.', sources: [CAREER_SEARCH_SOURCE],
  }),

  guide({
    id: 'interview-prepare-historias', pillar: 'interview', title: 'Prepare histórias antes da entrevista',
    promise: 'Chegue com exemplos reais para competências que a vaga deve avaliar.',
    context: 'Sob pressão, é fácil lembrar apenas de tarefas. Um banco de histórias ajuda a responder com contexto, decisões e resultados.',
    action: 'Liste seis situações: entrega difícil, conflito, erro, liderança, aprendizado e resultado. Para cada uma, registre seu papel e o que mudou.',
    before: 'Acho que já trabalhei com algo parecido, mas não lembro os detalhes.',
    after: 'Tenho uma história curta com situação, decisão, resultado e aprendizado.',
    second: 'Use histórias diferentes e verdadeiras. Adapte o foco à pergunta sem decorar um discurso rígido.',
    checklist: ['Seis situações', 'Seu papel explícito', 'Resultado lembrado', 'Aprendizado honesto'],
    cta: 'Escreva agora o título de seis histórias e escolha duas para ensaiar.', sources: [DOL_INTERVIEW_SOURCE, DOL_INTERVIEW_GUIDE],
  }),
  guide({
    id: 'interview-metodo-star', pillar: 'interview', title: 'Use STAR sem parecer que decorou a resposta',
    promise: 'Organize exemplos para responder com começo, ação e resultado.',
    context: 'STAR evita histórias confusas: situação, tarefa, ação e resultado. O maior espaço deve ficar naquilo que você fez e decidiu.',
    action: 'Resuma situação e tarefa em poucas frases. Detalhe sua ação em primeira pessoa e termine com resultado, feedback ou aprendizado.',
    before: 'O time teve um problema e no fim deu tudo certo.',
    after: 'Com 48 horas, priorizei duas falhas, coordenei rollback e reduzi o impacto a 12 minutos.',
    second: 'Não force resultado positivo. Em perguntas sobre erro, explique consequência, correção e o que mudou no seu processo.',
    checklist: ['Situação breve', 'Tarefa clara', 'Ação em primeira pessoa', 'Resultado ou aprendizado'],
    cta: 'Grave uma resposta de dois minutos e veja se a maior parte descreve sua ação.', sources: [DOL_INTERVIEW_SOURCE, DOL_INTERVIEW_GUIDE],
  }),
  guide({
    id: 'interview-comunique-raciocinio', pillar: 'interview', title: 'Mostre seu raciocínio quando não souber a resposta',
    promise: 'Transforme incerteza em uma demonstração de análise e colaboração.',
    context: 'Entrevistas avaliam como você estrutura problemas, não apenas memória. Inventar certeza costuma ser pior que explicitar hipóteses.',
    action: 'Confirme o objetivo, faça perguntas, declare suposições e avance em etapas. Compare opções e diga o que validaria primeiro.',
    before: 'Não sei. Ou talvez seja a opção A.',
    after: 'Não usei isso diretamente; eu começaria validando volume e consistência, depois compararia A e B.',
    second: 'Quando chegar ao limite, diga o que falta para concluir. Convide o entrevistador a esclarecer sem transferir todo o problema.',
    checklist: ['Objetivo confirmado', 'Hipóteses explícitas', 'Opções comparadas', 'Próximo teste definido'],
    cta: 'Pratique explicar um problema técnico em voz alta sem abrir o editor.', sources: [DOL_INTERVIEW_GUIDE],
  }),
  guide({
    id: 'interview-perguntas-ao-entrevistador', pillar: 'interview', title: 'Prepare perguntas que também avaliam a empresa',
    promise: 'Use o final da entrevista para entender trabalho, expectativas e ambiente.',
    context: 'A entrevista é uma conversa de avaliação mútua. Perguntas pesquisadas mostram preparo e ajudam você a decidir com mais informação.',
    action: 'Pergunte sobre sucesso nos primeiros meses, desafios atuais, decisões, colaboração e feedback. Adapte ao papel de quem entrevista.',
    before: 'Não tenho perguntas. Está tudo claro.',
    after: 'Qual problema faria vocês dizerem em seis meses que essa contratação deu certo?',
    second: 'Evite perguntar algo respondido facilmente no site. Salário e condições importam, mas escolha o momento adequado no processo.',
    checklist: ['Sucesso no cargo', 'Desafio real', 'Forma de colaboração', 'Próximos passos'],
    cta: 'Prepare cinco perguntas e marque quais servem para recrutador, liderança e pares.', sources: [DOL_INTERVIEW_SOURCE, DOL_INTERVIEW_GUIDE],
  }),
  guide({
    id: 'interview-entrevista-remota', pillar: 'interview', title: 'Prepare a entrevista remota além da câmera',
    promise: 'Reduza imprevistos e preserve energia para a conversa.',
    context: 'Problemas de áudio, conexão e ambiente afetam comunicação. Um teste simples evita começar a entrevista resolvendo logística.',
    action: 'Teste link, câmera, microfone, energia e conexão. Feche notificações, abra currículo e vaga e tenha um plano alternativo de contato.',
    before: 'Descobrir na hora que o navegador não tem acesso ao microfone.',
    after: 'Teste concluído, ambiente silencioso e telefone de backup disponível.',
    second: 'Olhe para a câmera em momentos-chave, mas não force contato constante. Avise cedo se surgir uma falha e proponha alternativa.',
    checklist: ['Link testado', 'Áudio confirmado', 'Notificações fechadas', 'Plano de backup'],
    cta: 'Faça um teste completo no mesmo dispositivo e ambiente da entrevista.', sources: [DOL_INTERVIEW_GUIDE],
  }),
  guide({
    id: 'interview-revisao-pos-entrevista', pillar: 'interview', title: 'Use o pós-entrevista para melhorar a próxima',
    promise: 'Registre sinais, dúvidas e aprendizados enquanto a conversa está fresca.',
    context: 'Sem revisão, detalhes desaparecem e os mesmos pontos fracos se repetem. O registro também ajuda a comparar oportunidades.',
    action: 'Anote perguntas, respostas fortes, pontos confusos, informações da empresa e próximos passos. Envie agradecimento curto se for adequado.',
    before: 'Acho que foi bem; agora é esperar.',
    after: 'Registrei 8 perguntas, 2 respostas para melhorar e o prazo combinado.',
    second: 'Não transforme cada silêncio em conclusão. Use apenas sinais observáveis e continue seu processo de busca enquanto aguarda.',
    checklist: ['Perguntas registradas', 'Respostas revisadas', 'Prazo anotado', 'Próxima melhoria definida'],
    cta: 'Crie uma nota padrão e preencha nos primeiros 15 minutos após cada entrevista.', sources: [DOL_INTERVIEW_SOURCE, DOL_INTERVIEW_GUIDE],
  }),
]);
