const LINKEDIN_PROFILE_SOURCE = Object.freeze({
  title: 'How do I create a good LinkedIn profile?',
  author: 'LinkedIn Help',
  url: 'https://www.linkedin.com/help/linkedin/answer/a554351/how-do-i-create-a-good-linkedin-profile-?lang=en',
});
const LINKEDIN_HEADLINE_SOURCE = Object.freeze({
  title: 'Edit the Introduction section on your profile',
  author: 'LinkedIn Help',
  url: 'https://www.linkedin.com/help/linkedin/answer/a1435876',
});
const LINKEDIN_LANGUAGE_SOURCE = Object.freeze({
  title: 'Create or delete a profile in another language',
  author: 'LinkedIn Help',
  url: 'https://www.linkedin.com/help/linkedin/answer/a541878/create-or-delete-a-profile-in-another-language?lang=en',
});
const LINKEDIN_ABOUT_SOURCE = Object.freeze({
  title: 'Edit the About section in your profile',
  author: 'LinkedIn Help',
  url: 'https://www.linkedin.com/help/linkedin/answer/a553140/edit-the-about-section-in-your-profile?lang=en',
});
const LINKEDIN_EXPERIENCE_SOURCE = Object.freeze({
  title: 'Manage your Experience section',
  author: 'LinkedIn Help',
  url: 'https://www.linkedin.com/help/linkedin/answer/a593695/manage-your-experience-section?lang=en',
});
const LINKEDIN_SKILLS_SOURCE = Object.freeze({
  title: 'Add and remove skills on your profile',
  author: 'LinkedIn Help',
  url: 'https://www.linkedin.com/help/linkedin/answer/a549047/add-and-remove-skills-on-your-profile?lang=en',
});
const LINKEDIN_FEATURED_SOURCE = Object.freeze({
  title: 'Featured section on your profile FAQs',
  author: 'LinkedIn Help',
  url: 'https://www.linkedin.com/help/linkedin/answer/a552452/featured-section-on-your-profile-faqs?lang=en',
});
const LINKEDIN_RECOMMENDATIONS_SOURCE = Object.freeze({
  title: 'Request a recommendation',
  author: 'LinkedIn Help',
  url: 'https://www.linkedin.com/help/linkedin/answer/a546682/request-a-recommendation?lang=en',
});
const LINKEDIN_CONTACT_SOURCE = Object.freeze({
  title: 'Contact Info Section of Your Profile',
  author: 'LinkedIn Help',
  url: 'https://www.linkedin.com/help/linkedin/answer/a565128/contact-info-section-of-your-profile?lang=en',
});
const LINKEDIN_ACTIVITY_SOURCE = Object.freeze({
  title: 'View your activity or a member\'s activity on LinkedIn',
  author: 'LinkedIn Help',
  url: 'https://www.linkedin.com/help/linkedin/answer/a546122/viewing-recent-activity?lang=en',
});
const LINKEDIN_OPEN_TO_WORK_SOURCE = Object.freeze({
  title: 'Let recruiters know you are Open to Work',
  author: 'LinkedIn Help',
  url: 'https://www.linkedin.com/help/linkedin/answer/a507508/making-your-profile-visible-or-hidden-from-recruiters?lang=en',
});
const HARVARD_RESUME_SOURCE = Object.freeze({
  title: 'Create a Resume or Cover Letter',
  author: 'Harvard FAS Mignone Center for Career Success',
  url: 'https://careerservices.fas.harvard.edu/resources/hes-create-impactful-resumes-and-cover-letters/',
});
const DOL_RESUME_SOURCE = Object.freeze({
  title: 'Resume Essentials Participant Guide',
  author: 'U.S. Department of Labor',
  url: 'https://www.dol.gov/sites/dolgov/files/VETS/files/ResumeEssentials_PG_Interactive_Feb2026.pdf',
});
const CAREER_SEARCH_SOURCE = Object.freeze({
  title: 'Job Search',
  author: 'CareerOneStop, U.S. Department of Labor',
  url: 'https://www.careeronestop.org/JobSearch/job-search.aspx',
});
const DOL_INTERVIEW_SOURCE = Object.freeze({
  title: 'Interview Tips',
  author: 'U.S. Department of Labor',
  url: 'https://www.dol.gov/general/jobs/interview-tips?lang=en',
});
const DOL_INTERVIEW_GUIDE = Object.freeze({
  title: 'Interview Skills Participant Guide',
  author: 'U.S. Department of Labor',
  url: 'https://www.dol.gov/sites/dolgov/files/VETS/files/InterviewSkills_PG_Interactive_Feb2026.pdf',
});

const PILLAR_LABEL = Object.freeze({
  linkedin: 'LINKEDIN',
  resume: 'RESUME',
  search: 'JOB SEARCH',
  application: 'APPLICATION',
  interview: 'INTERVIEW',
});

function guide({
  id, pillar, title, promise, context, action, actionTitle = 'Do this', before, after,
  second, secondTitle = 'A useful adjustment', checklist, cta, sources,
}) {
  return Object.freeze({
    id,
    version: '2',
    pillar,
    title,
    promise,
    slides: Object.freeze([
      Object.freeze({ kind: 'cover', title, body: promise }),
      Object.freeze({ kind: 'context', title: 'Why it matters', body: context }),
      Object.freeze({ kind: 'action', title: actionTitle, body: action }),
      Object.freeze({ kind: 'example', title: 'Before and after', before, after }),
      Object.freeze({ kind: 'action', title: secondTitle, body: second }),
      Object.freeze({ kind: 'checklist', title: 'Quick checklist', items: Object.freeze(checklist) }),
      Object.freeze({ kind: 'cta', title: 'Apply it today', body: cta }),
    ]),
    story: Object.freeze({
      eyebrow: PILLAR_LABEL[pillar],
      title,
      body: `${promise} Read the full guide in the feed.`,
    }),
    caption: Object.freeze({
      hook: promise,
      action: `${cta} Save this guide before your next application.`,
    }),
    hashtags: Object.freeze(['OpeningsDev', 'CareerTips', PILLAR_LABEL[pillar].replaceAll(' ', '')]),
    sources: Object.freeze(sources),
    minRepeatDays: 84,
  });
}

export const EDITORIAL_CATALOG = Object.freeze([
  guide({
    id: 'linkedin-headline-clara', pillar: 'linkedin', title: 'Make your LinkedIn headline say what you do',
    promise: 'Replace a loose keyword list with a clear role, specialty, and outcome.',
    context: 'Your headline appears in search results, comments, and connection requests. It should help a recruiter understand your work in a few seconds.',
    action: 'Use this structure: role or specialty + technology or sector + outcome. Choose terms that appear in target jobs and match your real experience.',
    before: 'Developer | Looking for opportunities',
    after: 'Backend Developer | Node.js and APIs | Reliable payment systems',
    second: 'Skip the long tool list. Two strong keywords and one useful outcome say more than ten disconnected terms.',
    checklist: ['Specific role', 'Two relevant keywords', 'Outcome or sector', 'No empty claims'],
    cta: 'Write one headline, then compare it with three roles you would apply for.', sources: [LINKEDIN_HEADLINE_SOURCE],
  }),
  guide({
    id: 'linkedin-idioma-do-perfil', pillar: 'linkedin', title: 'Match your LinkedIn language to your target market',
    promise: 'Make your profile easy to read without relying on improvised translation.',
    context: 'A profile aimed at international roles should present your work, results, and technical terms in the language used by those employers.',
    action: 'Choose one primary language for your main search. If you target two markets, create a secondary profile and keep facts and dates consistent.',
    before: 'English headline, mixed-language About section and experience',
    after: 'One complete primary profile and a consistent secondary version',
    second: 'Keep official company and product names unchanged. Translate the context, responsibility, and result for the reader.',
    checklist: ['Language matches target jobs', 'Sections stay consistent', 'Technical terms sound natural', 'Dates match in both versions'],
    cta: 'Review five target jobs and note which language dominates the descriptions.', sources: [LINKEDIN_LANGUAGE_SOURCE],
  }),
  guide({
    id: 'linkedin-sobre-que-posiciona', pillar: 'linkedin', title: 'Write an About section with focus and proof',
    promise: 'Connect your experience, strongest skills, and next direction in four short paragraphs.',
    context: 'Your About section should guide the reader, not repeat your full resume. It needs a clear focus and at least one reason to believe you.',
    action: 'Start with your role and focus. Add two strengths, one concrete result, and the kind of problem you want to solve next. Use first person.',
    before: 'Passionate technology professional who loves new challenges.',
    after: 'I build reliable data pipelines. A recent redesign cut payment processing time by 38%.',
    second: 'Use short paragraphs. Add keywords only where they describe work you have done. End with a specific professional direction.',
    checklist: ['Role and focus', 'Two useful strengths', 'One concrete result', 'Clear next direction'],
    cta: 'Draft four short paragraphs and remove every sentence that adds no evidence.', sources: [LINKEDIN_ABOUT_SOURCE],
  }),
  guide({
    id: 'linkedin-titulo-de-experiencia', pillar: 'linkedin', title: 'Use experience titles recruiters can understand',
    promise: 'Clarify an internal title without inventing seniority or hiding your specialty.',
    context: 'Internal job titles can be hard to recognize outside one company. A familiar term improves scanning when it remains faithful to the actual role.',
    action: 'Keep the official title and add a specialty in parentheses when needed. Use the description to explain scope, level, and decisions.',
    before: 'Ninja II',
    after: 'Software Engineer II (Backend)',
    second: 'Do not promote yourself in the title. Show seniority through complexity, ownership, decisions, and results in the experience details.',
    checklist: ['Accurate title', 'Clear specialty', 'Provable seniority', 'Recognizable terms'],
    cta: 'Review every internal title that an external recruiter may not understand.', sources: [LINKEDIN_EXPERIENCE_SOURCE],
  }),
  guide({
    id: 'linkedin-resultados-na-experiencia', pillar: 'linkedin', title: 'Turn LinkedIn duties into outcomes',
    promise: 'Show how your work changed a product, process, cost, risk, or customer result.',
    context: 'A duty list describes what the role required. Outcomes show what you delivered and give the reader a reason to trust your experience.',
    action: 'Write each point as action + context + result. If revenue is not relevant, use scale, time, adoption, quality, or risk.',
    before: 'Responsible for building APIs and fixing bugs.',
    after: 'Redesigned 6 critical APIs and cut integration failures by 31% in four months.',
    second: 'Use a specific verb and explain what the number compares. An honest estimate with context is better than a large number with no basis.',
    checklist: ['Specific action', 'Defined scope', 'Observed result', 'Metric with context'],
    cta: 'Rewrite the first point in your most recent experience today.', sources: [LINKEDIN_EXPERIENCE_SOURCE],
  }),
  guide({
    id: 'linkedin-skills-encontraveis', pillar: 'linkedin', title: 'Make your LinkedIn skills match your target role',
    promise: 'Keep a focused skill list that reflects both your target jobs and your real work.',
    context: 'A generic skill list weakens your positioning. Your main skills should match the work you want and the evidence already on your profile.',
    action: 'Collect repeated terms from ten realistic jobs. Keep only skills you can discuss, then connect important skills to related experience.',
    before: 'A long mix of Office, leadership, Java, design, and marketing',
    after: 'A focused set of backend, API, database, and cloud skills',
    second: 'Order skills by relevance to your target role, not by the date you added them. Remove stale or unrelated items.',
    checklist: ['Terms from target jobs', 'Skills you can prove', 'Links to real experience', 'Current priorities first'],
    cta: 'Compare your first ten skills with the requirements in three target jobs.', sources: [LINKEDIN_SKILLS_SOURCE],
  }),
  guide({
    id: 'linkedin-provas-em-destaque', pillar: 'linkedin', title: 'Use Featured to show proof, not clutter',
    promise: 'Point recruiters to work samples that support the claims on your profile.',
    context: 'Saying you can do the work is different from showing it. A focused Featured section shortens the path from claim to evidence.',
    action: 'Choose two to four items tied to your target role: a case study, explained repository, article, talk, demo, or portfolio.',
    before: 'Old links with no title or explanation',
    after: 'Case study: cloud migration cut monthly cost by 24%, with context and decisions',
    second: 'Give each item a title that explains its value. Remove broken, confidential, unclear, or unrelated material.',
    checklist: ['Relevant proof', 'Useful title', 'Working link', 'No confidential data'],
    cta: 'Choose one real work sample and write one line explaining why it matters.', sources: [LINKEDIN_FEATURED_SOURCE],
  }),
  guide({
    id: 'linkedin-recomendacoes-que-comprovam', pillar: 'linkedin', title: 'Ask for recommendations with useful context',
    promise: 'Help a former colleague describe your work with more than a generic compliment.',
    context: 'A useful recommendation explains the working relationship, a real situation, and your contribution. Praise alone adds little evidence.',
    action: 'Ask someone who saw your work closely. Mention the project, your responsibility, and the result so the request is easy to answer.',
    before: 'Could you write me a recommendation?',
    after: 'Could you mention our migration, my role in the decision, and the effect on the team?',
    second: 'Seek different viewpoints from a manager, peer, or partner team. Do not write the final recommendation for them.',
    checklist: ['Real working relationship', 'Specific project', 'Clear contribution', 'Different viewpoints'],
    cta: 'Choose one person and send a short request with enough context.', sources: [LINKEDIN_RECOMMENDATIONS_SOURCE],
  }),
  guide({
    id: 'linkedin-contexto-remoto', pillar: 'linkedin', title: 'Show how you work with remote teams',
    promise: 'Prove distributed collaboration instead of adding the word remote to your profile.',
    context: 'Remote work depends on communication, ownership, and coordination across schedules. Those skills are stronger when tied to real situations.',
    action: 'Mention distributed teams, time zones, async routines, documentation, and how your approach reduced delays or confusion.',
    before: 'Experienced in remote work.',
    after: 'Coordinated async releases across Brazil and Europe, cutting delivery blockers by 20%.',
    second: 'State your location and work preference clearly. Do not promise hours or time-zone coverage you cannot sustain.',
    checklist: ['Distributed team context', 'Communication practice', 'Observed result', 'Realistic availability'],
    cta: 'Add one proof of remote collaboration to the most relevant experience.', sources: [LINKEDIN_PROFILE_SOURCE],
  }),
  guide({
    id: 'linkedin-contato-profissional', pillar: 'linkedin', title: 'Make it easy to contact you',
    promise: 'Give a recruiter one clear professional path to start a conversation.',
    context: 'A strong profile still loses opportunities when contact details are hidden, stale, or broken. Privacy remains part of the decision.',
    action: 'Review your professional email, portfolio, location, and profile URL. Share only the details needed for an initial conversation.',
    before: 'Old email and a broken portfolio link',
    after: 'Current email, clean profile URL, and a working portfolio',
    second: 'Test every link in a private window. Keep your home address, personal documents, and unnecessary phone details private.',
    checklist: ['Current email', 'Clean profile URL', 'Tested portfolio', 'Privacy reviewed'],
    cta: 'View your profile as a visitor and test every contact path.', sources: [LINKEDIN_CONTACT_SOURCE],
  }),
  guide({
    id: 'linkedin-atividade-estrategica', pillar: 'linkedin', title: 'Make your LinkedIn activity support your profile',
    promise: 'Use posts and comments to show how you think about the work you want.',
    context: 'Your activity is part of your professional impression. Useful participation can show judgment, clarity, and genuine interest in the field.',
    action: 'Comment with a relevant example, data point, or question. When you post, explain the context, decision, and result.',
    before: 'Great post. Thanks for sharing!',
    after: 'We saw this trade-off in checkout. Measuring errors by step changed our priority.',
    second: 'Choose consistency over volume. Two useful contributions a week say more than generic comments on dozens of posts.',
    checklist: ['Relevant topic', 'Concrete contribution', 'Professional tone', 'Sustainable pace'],
    cta: 'Write one comment today that adds an example, question, or useful counterpoint.', sources: [LINKEDIN_ACTIVITY_SOURCE],
  }),
  guide({
    id: 'linkedin-privacidade-open-to-work', pillar: 'linkedin', title: 'Use Open to Work with the right privacy setting',
    promise: 'Signal what you want with role, location, work model, and visibility choices.',
    context: 'Specific preferences help recruiters assess fit. Your visibility setting should also match your current employment and privacy needs.',
    action: 'Set realistic roles, locations, work models, and start dates. Choose whether all members or recruiters only can see the signal.',
    before: 'Open to any opportunity, anywhere',
    after: 'Backend Engineer, remote in Brazil or hybrid in Sao Paulo, available in 30 days',
    second: 'Review the settings when your search changes. A platform signal does not replace a focused search and direct applications.',
    checklist: ['Defined roles', 'Realistic locations', 'Preferred work model', 'Intentional visibility'],
    cta: 'Open your preferences and remove any option you would not actually accept.', sources: [LINKEDIN_OPEN_TO_WORK_SOURCE],
  }),

  guide({
    id: 'resume-resumo-direto', pillar: 'resume', title: 'Escreva um resumo de currículo que chega ao ponto',
    promise: 'Apresente função, especialidade e evidência em poucas linhas.',
    context: 'O topo do currículo precisa orientar a leitura. Objetivos genéricos ocupam espaço sem explicar por que você combina com a vaga.',
    action: 'Use três linhas: identidade profissional, competências centrais e uma prova relacionada ao cargo. Ajuste os termos para cada vaga.',
    before: 'Busco uma oportunidade para crescer e contribuir com a empresa.',
    after: 'Product Designer com 5 anos em SaaS B2B; redesenho de onboarding elevou ativação em 18%.',
    second: 'Evite adjetivos sem prova. Se você está no início, troque anos de experiência por projeto relevante, domínio técnico e contexto.',
    checklist: ['Cargo-alvo', 'Especialidade', 'Evidência concreta', 'Até quatro linhas'],
    cta: 'Corte a frase que serviria para qualquer candidato e inclua uma prova sua.', sources: [HARVARD_RESUME_SOURCE, DOL_RESUME_SOURCE],
  }),
  guide({
    id: 'resume-bullets-de-impacto', pillar: 'resume', title: 'Transforme responsabilidades em bullets de impacto',
    promise: 'Mostre ação, contexto e efeito em cada ponto do currículo.',
    context: 'Responsabilidades descrevem o cargo; realizações diferenciam o candidato. Cada bullet deve tornar uma contribuição fácil de escanear.',
    action: 'Comece com verbo forte, diga o que mudou e encerre com resultado ou escala. Um bullet deve carregar uma ideia principal.',
    before: 'Responsável por testes do sistema.',
    after: 'Automatizei 140 testes críticos e reduzi regressões em produção em 27%.',
    second: 'Ordene os bullets por relevância para a vaga, não por cronologia da tarefa. Mantenha de três a cinco pontos fortes por experiência.',
    checklist: ['Verbo específico', 'Uma ideia por bullet', 'Resultado ou escala', 'Ordem por relevância'],
    cta: 'Reescreva o bullet mais genérico da sua experiência recente.', sources: [HARVARD_RESUME_SOURCE, DOL_RESUME_SOURCE],
  }),
  guide({
    id: 'resume-metricas-com-contexto', pillar: 'resume', title: 'Use métricas no currículo sem inventar precisão',
    promise: 'Dê dimensão às entregas com números honestos e explicados.',
    context: 'Métricas ajudam o leitor a avaliar escala e impacto. Sem contexto, porém, o número pode parecer decorativo ou pouco confiável.',
    action: 'Procure volume, tempo, adoção, qualidade, custo, receita ou risco. Explique a comparação: antes e depois, período ou universo medido.',
    before: 'Melhorei bastante a performance da aplicação.',
    after: 'Reduzi o p95 de 1,8 s para 900 ms em três rotas usadas por 60 mil clientes.',
    second: 'Se o dado exato for confidencial, use percentual, faixa ou escala aproximada e sinalize o contexto sem revelar informação protegida.',
    checklist: ['Métrica verificável', 'Base de comparação', 'Período ou escala', 'Sem dado confidencial'],
    cta: 'Liste três entregas e associe a cada uma um indicador que você consegue defender.', sources: [HARVARD_RESUME_SOURCE, DOL_RESUME_SOURCE],
  }),
  guide({
    id: 'resume-formato-ats', pillar: 'resume', title: 'Deixe seu currículo fácil de ler por pessoas e sistemas',
    promise: 'Use uma estrutura simples para evitar que informação importante se perca.',
    context: 'Layouts complexos podem prejudicar leitura e extração de dados. Clareza visual também ajuda quem faz a primeira triagem rapidamente.',
    action: 'Prefira uma coluna, títulos convencionais, ordem cronológica reversa e texto selecionável. Use datas e cargos com formato consistente.',
    before: 'Duas colunas, barras de skill, ícones e informações dentro de imagens',
    after: 'Seções claras, texto real, hierarquia simples e datas consistentes',
    second: 'Exporte em PDF quando solicitado e confira se copiar e colar preserva a ordem. Siga o formato pedido no anúncio.',
    checklist: ['Uma coluna', 'Títulos convencionais', 'Texto selecionável', 'Arquivo solicitado'],
    cta: 'Copie o texto do PDF para um editor simples e veja se a ordem continua lógica.', sources: [HARVARD_RESUME_SOURCE, DOL_RESUME_SOURCE],
  }),
  guide({
    id: 'resume-curriculo-por-vaga', pillar: 'resume', title: 'Adapte o currículo para a vaga sem reescrever sua história',
    promise: 'Mude ênfase e ordem para tornar o encaixe evidente.',
    context: 'Um currículo único tende a destacar informação irrelevante. Adaptar não é inventar: é selecionar as provas mais úteis para aquela oportunidade.',
    action: 'Marque requisitos obrigatórios e preferenciais. Reordene resumo, competências e bullets para colocar evidências correspondentes primeiro.',
    before: 'Mesmo currículo enviado para frontend, dados e gestão',
    after: 'Versão que prioriza as experiências compatíveis com cada função',
    second: 'Use a linguagem da vaga quando ela descreve algo que você realmente fez. Não copie blocos inteiros nem inclua competência sem prova.',
    checklist: ['Requisitos marcados', 'Resumo ajustado', 'Provas priorizadas', 'Sem exagero'],
    cta: 'Antes do próximo envio, escolha os três requisitos que seu currículo precisa provar.', sources: [HARVARD_RESUME_SOURCE, DOL_RESUME_SOURCE],
  }),
  guide({
    id: 'resume-projetos-relevantes', pillar: 'resume', title: 'Use projetos para provar experiência relevante',
    promise: 'Dê peso a projetos pessoais, acadêmicos ou voluntários com contexto e resultado.',
    context: 'Projetos podem fechar lacunas de experiência quando demonstram decisões e habilidades próximas do trabalho desejado.',
    action: 'Inclua problema, seu papel, escolhas técnicas e resultado. Se houve equipe, deixe clara sua contribuição individual.',
    before: 'Projeto de e-commerce em React.',
    after: 'Criei checkout acessível em React; conduzi testes com 8 usuários e corrigi 12 barreiras de navegação.',
    second: 'Selecione poucos projetos fortes. Link só ajuda se estiver funcionando, tiver instruções claras e não expuser segredos.',
    checklist: ['Problema definido', 'Papel individual', 'Decisões explicadas', 'Resultado ou aprendizado'],
    cta: 'Escolha o projeto mais alinhado à vaga e reescreva sua descrição em três bullets.', sources: [HARVARD_RESUME_SOURCE, DOL_RESUME_SOURCE],
  }),
  guide({
    id: 'resume-portfolio-que-prova', pillar: 'resume', title: 'Conecte o currículo a um portfólio que prova seu trabalho',
    promise: 'Faça cada link levar a uma evidência clara, curta e acessível.',
    context: 'Um portfólio sem contexto transfere trabalho para o recrutador. O material precisa explicar problema, participação e raciocínio.',
    action: 'Para cada case, apresente cenário, restrições, decisões, contribuição e resultado. Mostre o suficiente para avaliar sem revelar material confidencial.',
    before: 'Galeria de telas sem explicação.',
    after: 'Case com problema, opções consideradas, decisão tomada e impacto medido.',
    second: 'Use URLs estáveis e títulos descritivos. Teste em celular e janela anônima para evitar acesso bloqueado.',
    checklist: ['Case com contexto', 'Autoria explícita', 'Decisão demonstrada', 'Link público testado'],
    cta: 'Abra seu principal case como visitante e anote o que não se entende em 30 segundos.', sources: [HARVARD_RESUME_SOURCE],
  }),
  guide({
    id: 'resume-revisao-final', pillar: 'resume', title: 'Faça uma revisão final que evita eliminações bobas',
    promise: 'Confira conteúdo, consistência e arquivo antes de enviar.',
    context: 'Erros pequenos podem gerar dúvida sobre atenção a detalhes. Uma rotina curta de revisão reduz risco sem travar a candidatura.',
    action: 'Leia o currículo fora do editor e depois em voz alta. Compare cargo, empresa e requisitos com o anúncio mais uma vez.',
    before: 'curriculo_final_agora-v3.pdf com link quebrado e data diferente',
    after: 'nome-sobrenome-cargo.pdf, datas consistentes e links verificados',
    second: 'Peça a alguém para responder: “qual é a principal força deste candidato?” Se a resposta não for clara, ajuste a hierarquia.',
    checklist: ['Ortografia revisada', 'Datas consistentes', 'Links testados', 'Nome de arquivo claro'],
    cta: 'Crie uma checklist fixa e só marque a candidatura como pronta depois dos quatro itens.', sources: [HARVARD_RESUME_SOURCE, DOL_RESUME_SOURCE],
  }),

  guide({
    id: 'search-busca-com-criterios', pillar: 'search', title: 'Defina critérios antes de abrir mais uma lista de vagas',
    promise: 'Concentre energia em oportunidades que você realmente aceitaria.',
    context: 'Buscar sem critérios aumenta volume e reduz qualidade. Limites claros ajudam a comparar vagas e personalizar candidaturas.',
    action: 'Defina função, senioridade, faixa, localidade, formato, setores e restrições. Separe o que é obrigatório do que é preferência.',
    before: 'Candidatar a qualquer vaga de tecnologia.',
    after: 'Backend pleno, remoto no Brasil, produto B2B e faixa mínima definida.',
    second: 'Revise os critérios com dados reais a cada duas semanas. Ajuste expectativas sem abandonar necessidades importantes.',
    checklist: ['Função-alvo', 'Faixa mínima', 'Local e formato', 'Restrições claras'],
    cta: 'Escreva seus quatro critérios obrigatórios antes da próxima busca.', sources: [CAREER_SEARCH_SOURCE],
  }),
  guide({
    id: 'search-alertas-uteis', pillar: 'search', title: 'Crie alertas de vagas que não viram ruído',
    promise: 'Receba oportunidades mais próximas do seu objetivo e aja cedo.',
    context: 'Alertas amplos lotam a caixa de entrada e escondem boas oportunidades. Combinações menores produzem sinais melhores.',
    action: 'Crie alertas separados por título, senioridade e local. Inclua sinônimos reais da função e exclua termos que geram falsos positivos quando possível.',
    before: 'Um alerta para “developer”.',
    after: 'Alertas para “backend engineer”, “node developer” e “API engineer”, remoto Brasil.',
    second: 'Reserve dois horários curtos para triagem. Desative alertas que não geram vagas compatíveis depois de uma semana.',
    checklist: ['Título específico', 'Sinônimos úteis', 'Local definido', 'Revisão semanal'],
    cta: 'Divida seu alerta mais amplo em duas buscas mais específicas.', sources: [CAREER_SEARCH_SOURCE],
  }),
  guide({
    id: 'search-fontes-alem-do-linkedin', pillar: 'search', title: 'Procure vagas além de uma única plataforma',
    promise: 'Amplie a cobertura sem transformar a busca em navegação infinita.',
    context: 'Empresas publicam em canais diferentes e algumas oportunidades aparecem primeiro em páginas próprias ou comunidades especializadas.',
    action: 'Monte uma lista curta com agregador, páginas de empresas-alvo, comunidades do setor e sua rede. Dê um horário para cada fonte.',
    before: 'Atualizar o mesmo feed várias vezes por dia.',
    after: 'Rotina com agregador, 15 empresas-alvo e duas comunidades relevantes.',
    second: 'Registre a origem de cada vaga. Depois de quatro semanas, mantenha as fontes que realmente geram conversas ou oportunidades compatíveis.',
    checklist: ['Agregador confiável', 'Empresas-alvo', 'Comunidades relevantes', 'Origem registrada'],
    cta: 'Escolha hoje cinco empresas e salve a página de carreiras de cada uma.', sources: [CAREER_SEARCH_SOURCE],
  }),
  guide({
    id: 'search-pesquisa-de-empresa', pillar: 'search', title: 'Pesquise a empresa antes de investir na candidatura',
    promise: 'Descubra contexto, riscos e argumentos para personalizar sua abordagem.',
    context: 'Uma vaga não mostra toda a realidade do trabalho. Pesquisa reduz surpresas e melhora currículo, mensagem e entrevista.',
    action: 'Verifique produto, clientes, modelo de negócio, notícias, liderança, cultura publicada e pessoas da área. Compare fontes.',
    before: 'A empresa parece legal e usa a tecnologia que eu gosto.',
    after: 'Entendo o produto, o estágio do negócio e dois desafios prováveis da equipe.',
    second: 'Separe fato, opinião e hipótese. Avaliações anônimas ajudam como sinal, mas não devem ser a única base da decisão.',
    checklist: ['Produto entendido', 'Momento do negócio', 'Equipe localizada', 'Riscos anotados'],
    cta: 'Antes de aplicar, escreva duas razões específicas para querer conversar com a empresa.', sources: [CAREER_SEARCH_SOURCE],
  }),
  guide({
    id: 'search-networking-intencional', pillar: 'search', title: 'Faça networking sem pedir emprego no primeiro contato',
    promise: 'Construa conversas úteis com contexto, respeito e reciprocidade.',
    context: 'Networking funciona melhor como troca de informação e relação profissional. Pedidos vagos transferem esforço para quem recebe.',
    action: 'Aproxime-se por interesse específico: trabalho publicado, experiência no setor ou decisão de carreira. Faça uma pergunta curta e pesquisada.',
    before: 'Oi, tem vaga aí? Pode me indicar?',
    after: 'Vi sua migração para dados. Que habilidade mais pesou na transição para esse time?',
    second: 'Respeite o tempo da pessoa e não cobre resposta. Compartilhe algo útil quando fizer sentido e mantenha a relação além da necessidade imediata.',
    checklist: ['Contexto específico', 'Pergunta curta', 'Sem pressão', 'Reciprocidade possível'],
    cta: 'Escolha uma pessoa do seu campo e escreva uma mensagem com contexto real.', sources: [CAREER_SEARCH_SOURCE],
  }),
  guide({
    id: 'search-rotina-semanal', pillar: 'search', title: 'Monte uma rotina de busca que você consegue sustentar',
    promise: 'Troque ansiedade e volume por um processo semanal mensurável.',
    context: 'Buscar emprego envolve descoberta, pesquisa, adaptação e acompanhamento. Fazer tudo ao mesmo tempo torna o progresso invisível.',
    action: 'Distribua blocos: buscar, selecionar, adaptar, conversar e acompanhar. Defina metas de qualidade, como candidaturas compatíveis e contatos relevantes.',
    before: 'Passar horas rolando vagas e enviar quando der.',
    after: '3 blocos de 45 minutos, 4 boas candidaturas e 2 conversas por semana.',
    second: 'Registre data, vaga, versão do currículo, contato e próximo passo. Revise o funil para descobrir onde precisa melhorar.',
    checklist: ['Blocos no calendário', 'Meta de qualidade', 'Acompanhamento registrado', 'Revisão semanal'],
    cta: 'Reserve agora três blocos curtos para a próxima semana.', sources: [CAREER_SEARCH_SOURCE],
  }),

  guide({
    id: 'application-leia-os-requisitos', pillar: 'application', title: 'Leia requisitos antes de decidir não se candidatar',
    promise: 'Separe o essencial do desejável e avalie seu encaixe com evidências.',
    context: 'Descrições misturam responsabilidades, requisitos obrigatórios e preferências. Tratar tudo como eliminatório exclui boas candidaturas.',
    action: 'Marque cada item como obrigatório, preferencial ou contexto. Para os essenciais, anote uma evidência; para lacunas, avalie impacto e aprendizado.',
    before: 'Não tenho 100% dos itens, então não vou aplicar.',
    after: 'Atendo aos essenciais e consigo explicar duas lacunas preferenciais.',
    second: 'Não ignore exigências legais, idioma necessário ou disponibilidade essencial. Use julgamento, não uma porcentagem mágica.',
    checklist: ['Obrigatórios separados', 'Preferenciais separados', 'Evidências anotadas', 'Lacunas avaliadas'],
    cta: 'Pegue uma vaga salva e classifique os requisitos em três grupos.', sources: [DOL_RESUME_SOURCE, CAREER_SEARCH_SOURCE],
  }),
  guide({
    id: 'application-evidencias-de-fit', pillar: 'application', title: 'Construa uma tabela de evidências antes de aplicar',
    promise: 'Conecte cada requisito importante a uma prova concreta da sua trajetória.',
    context: 'A candidatura fica mais forte quando currículo e respostas mostram correspondência explícita, sem obrigar o leitor a deduzir.',
    action: 'Crie duas colunas: requisito e evidência. Use projeto, resultado, decisão ou aprendizado real. Depois leve as melhores provas ao currículo.',
    before: 'Tenho perfil para a vaga.',
    after: 'Requisito: APIs. Evidência: 6 APIs redesenhadas, 31% menos falhas.',
    second: 'Se faltar prova, não invente. Decida entre destacar experiência transferível, produzir um projeto ou reconhecer uma lacuna.',
    checklist: ['Requisitos prioritários', 'Uma prova por requisito', 'Métrica quando existe', 'Lacunas honestas'],
    cta: 'Faça a tabela para os cinco requisitos mais importantes da próxima vaga.', sources: [DOL_RESUME_SOURCE],
  }),
  guide({
    id: 'application-respostas-concisas', pillar: 'application', title: 'Responda formulários de candidatura com clareza',
    promise: 'Use respostas curtas que entregam contexto, ação e resultado.',
    context: 'Perguntas abertas avaliam comunicação e aderência. Textos longos demais escondem a evidência; respostas vagas não permitem avaliação.',
    action: 'Responda primeiro à pergunta. Em seguida, traga um exemplo com situação, sua ação e resultado. Corte introduções genéricas.',
    before: 'Sempre fui apaixonado por desafios e acredito que posso contribuir muito.',
    after: 'Liderei a correção do checkout em 48 horas; a recuperação reduziu abandono em 9%.',
    second: 'Não reutilize a mesma resposta sem revisar. Confirme limite, idioma e se cada frase ajuda a comprovar o que foi perguntado.',
    checklist: ['Pergunta respondida', 'Exemplo específico', 'Ação individual', 'Resultado claro'],
    cta: 'Revise sua última resposta e mova a evidência para a primeira metade.', sources: [DOL_RESUME_SOURCE],
  }),
  guide({
    id: 'application-follow-up-profissional', pillar: 'application', title: 'Faça follow-up sem pressionar o recrutador',
    promise: 'Reforce interesse e contexto com uma mensagem curta e útil.',
    context: 'Um acompanhamento pode facilitar a retomada da conversa. Mensagens frequentes ou sem informação nova tendem a criar ruído.',
    action: 'Espere o prazo informado. Sem prazo, use alguns dias úteis. Identifique vaga, data, interesse específico e disponibilidade para complementar dados.',
    before: 'Oi, alguma novidade? Estou aguardando urgente.',
    after: 'Olá, enviei minha candidatura para Backend em 2/9. O desafio de APIs distribuídas me interessa; sigo disponível.',
    second: 'Envie uma vez pelo canal adequado. Se não houver resposta, continue outras oportunidades em vez de insistir repetidamente.',
    checklist: ['Prazo respeitado', 'Vaga identificada', 'Interesse específico', 'Tom sem cobrança'],
    cta: 'Prepare um modelo de quatro linhas e personalize o motivo de interesse.', sources: [CAREER_SEARCH_SOURCE],
  }),

  guide({
    id: 'interview-prepare-historias', pillar: 'interview', title: 'Prepare histórias antes da entrevista',
    promise: 'Chegue com exemplos reais para competências que a vaga deve avaliar.',
    context: 'Sob pressão, é fácil lembrar apenas de tarefas. Um banco de histórias ajuda a responder com contexto, decisões e resultados.',
    action: 'Liste seis situações: entrega difícil, conflito, erro, liderança, aprendizado e resultado. Para cada uma, registre seu papel e o que mudou.',
    before: 'Acho que já trabalhei com algo parecido, mas não lembro os detalhes.',
    after: 'Tenho uma história curta com situação, decisão, resultado e aprendizado.',
    second: 'Use histórias diferentes e verdadeiras. Adapte o foco à pergunta sem decorar um discurso rígido.',
    checklist: ['Seis situações', 'Seu papel explícito', 'Resultado lembrado', 'Aprendizado honesto'],
    cta: 'Escreva agora o título de seis histórias e escolha duas para ensaiar.', sources: [DOL_INTERVIEW_SOURCE, DOL_INTERVIEW_GUIDE],
  }),
  guide({
    id: 'interview-metodo-star', pillar: 'interview', title: 'Use STAR sem parecer que decorou a resposta',
    promise: 'Organize exemplos para responder com começo, ação e resultado.',
    context: 'STAR evita histórias confusas: situação, tarefa, ação e resultado. O maior espaço deve ficar naquilo que você fez e decidiu.',
    action: 'Resuma situação e tarefa em poucas frases. Detalhe sua ação em primeira pessoa e termine com resultado, feedback ou aprendizado.',
    before: 'O time teve um problema e no fim deu tudo certo.',
    after: 'Com 48 horas, priorizei duas falhas, coordenei rollback e reduzi o impacto a 12 minutos.',
    second: 'Não force resultado positivo. Em perguntas sobre erro, explique consequência, correção e o que mudou no seu processo.',
    checklist: ['Situação breve', 'Tarefa clara', 'Ação em primeira pessoa', 'Resultado ou aprendizado'],
    cta: 'Grave uma resposta de dois minutos e veja se a maior parte descreve sua ação.', sources: [DOL_INTERVIEW_SOURCE, DOL_INTERVIEW_GUIDE],
  }),
  guide({
    id: 'interview-comunique-raciocinio', pillar: 'interview', title: 'Mostre seu raciocínio quando não souber a resposta',
    promise: 'Transforme incerteza em uma demonstração de análise e colaboração.',
    context: 'Entrevistas avaliam como você estrutura problemas, não apenas memória. Inventar certeza costuma ser pior que explicitar hipóteses.',
    action: 'Confirme o objetivo, faça perguntas, declare suposições e avance em etapas. Compare opções e diga o que validaria primeiro.',
    before: 'Não sei. Ou talvez seja a opção A.',
    after: 'Não usei isso diretamente; eu começaria validando volume e consistência, depois compararia A e B.',
    second: 'Quando chegar ao limite, diga o que falta para concluir. Convide o entrevistador a esclarecer sem transferir todo o problema.',
    checklist: ['Objetivo confirmado', 'Hipóteses explícitas', 'Opções comparadas', 'Próximo teste definido'],
    cta: 'Pratique explicar um problema técnico em voz alta sem abrir o editor.', sources: [DOL_INTERVIEW_GUIDE],
  }),
  guide({
    id: 'interview-perguntas-ao-entrevistador', pillar: 'interview', title: 'Prepare perguntas que também avaliam a empresa',
    promise: 'Use o final da entrevista para entender trabalho, expectativas e ambiente.',
    context: 'A entrevista é uma conversa de avaliação mútua. Perguntas pesquisadas mostram preparo e ajudam você a decidir com mais informação.',
    action: 'Pergunte sobre sucesso nos primeiros meses, desafios atuais, decisões, colaboração e feedback. Adapte ao papel de quem entrevista.',
    before: 'Não tenho perguntas. Está tudo claro.',
    after: 'Qual problema faria vocês dizerem em seis meses que essa contratação deu certo?',
    second: 'Evite perguntar algo respondido facilmente no site. Salário e condições importam, mas escolha o momento adequado no processo.',
    checklist: ['Sucesso no cargo', 'Desafio real', 'Forma de colaboração', 'Próximos passos'],
    cta: 'Prepare cinco perguntas e marque quais servem para recrutador, liderança e pares.', sources: [DOL_INTERVIEW_SOURCE, DOL_INTERVIEW_GUIDE],
  }),
  guide({
    id: 'interview-entrevista-remota', pillar: 'interview', title: 'Prepare a entrevista remota além da câmera',
    promise: 'Reduza imprevistos e preserve energia para a conversa.',
    context: 'Problemas de áudio, conexão e ambiente afetam comunicação. Um teste simples evita começar a entrevista resolvendo logística.',
    action: 'Teste link, câmera, microfone, energia e conexão. Feche notificações, abra currículo e vaga e tenha um plano alternativo de contato.',
    before: 'Descobrir na hora que o navegador não tem acesso ao microfone.',
    after: 'Teste concluído, ambiente silencioso e telefone de backup disponível.',
    second: 'Olhe para a câmera em momentos-chave, mas não force contato constante. Avise cedo se surgir uma falha e proponha alternativa.',
    checklist: ['Link testado', 'Áudio confirmado', 'Notificações fechadas', 'Plano de backup'],
    cta: 'Faça um teste completo no mesmo dispositivo e ambiente da entrevista.', sources: [DOL_INTERVIEW_GUIDE],
  }),
  guide({
    id: 'interview-revisao-pos-entrevista', pillar: 'interview', title: 'Use o pós-entrevista para melhorar a próxima',
    promise: 'Registre sinais, dúvidas e aprendizados enquanto a conversa está fresca.',
    context: 'Sem revisão, detalhes desaparecem e os mesmos pontos fracos se repetem. O registro também ajuda a comparar oportunidades.',
    action: 'Anote perguntas, respostas fortes, pontos confusos, informações da empresa e próximos passos. Envie agradecimento curto se for adequado.',
    before: 'Acho que foi bem; agora é esperar.',
    after: 'Registrei 8 perguntas, 2 respostas para melhorar e o prazo combinado.',
    second: 'Não transforme cada silêncio em conclusão. Use apenas sinais observáveis e continue seu processo de busca enquanto aguarda.',
    checklist: ['Perguntas registradas', 'Respostas revisadas', 'Prazo anotado', 'Próxima melhoria definida'],
    cta: 'Crie uma nota padrão e preencha nos primeiros 15 minutos após cada entrevista.', sources: [DOL_INTERVIEW_SOURCE, DOL_INTERVIEW_GUIDE],
  }),
]);
