const LINKEDIN_PROFILE_SOURCE = Object.freeze({
  title: 'How do I create a good LinkedIn profile?',
  author: 'LinkedIn Help',
  url: 'https://www.linkedin.com/help/linkedin/answer/a554351/how-do-i-create-a-good-linkedin-profile-?lang=en',
});
const LINKEDIN_HEADLINE_SOURCE = Object.freeze({
  title: 'Edit the Introduction section on your profile',
  author: 'LinkedIn Help',
  url: 'https://www.linkedin.com/help/linkedin/answer/a1435876',
});
const LINKEDIN_LANGUAGE_SOURCE = Object.freeze({
  title: 'Create or delete a profile in another language',
  author: 'LinkedIn Help',
  url: 'https://www.linkedin.com/help/linkedin/answer/a541878/create-or-delete-a-profile-in-another-language?lang=en',
});
const LINKEDIN_ABOUT_SOURCE = Object.freeze({
  title: 'Edit the About section in your profile',
  author: 'LinkedIn Help',
  url: 'https://www.linkedin.com/help/linkedin/answer/a553140/edit-the-about-section-in-your-profile?lang=en',
});
const LINKEDIN_EXPERIENCE_SOURCE = Object.freeze({
  title: 'Manage your Experience section',
  author: 'LinkedIn Help',
  url: 'https://www.linkedin.com/help/linkedin/answer/a593695/manage-your-experience-section?lang=en',
});
const LINKEDIN_SKILLS_SOURCE = Object.freeze({
  title: 'Add and remove skills on your profile',
  author: 'LinkedIn Help',
  url: 'https://www.linkedin.com/help/linkedin/answer/a549047/add-and-remove-skills-on-your-profile?lang=en',
});
const LINKEDIN_FEATURED_SOURCE = Object.freeze({
  title: 'Featured section on your profile FAQs',
  author: 'LinkedIn Help',
  url: 'https://www.linkedin.com/help/linkedin/answer/a552452/featured-section-on-your-profile-faqs?lang=en',
});
const LINKEDIN_RECOMMENDATIONS_SOURCE = Object.freeze({
  title: 'Request a recommendation',
  author: 'LinkedIn Help',
  url: 'https://www.linkedin.com/help/linkedin/answer/a546682/request-a-recommendation?lang=en',
});
const LINKEDIN_CONTACT_SOURCE = Object.freeze({
  title: 'Contact Info Section of Your Profile',
  author: 'LinkedIn Help',
  url: 'https://www.linkedin.com/help/linkedin/answer/a565128/contact-info-section-of-your-profile?lang=en',
});
const LINKEDIN_ACTIVITY_SOURCE = Object.freeze({
  title: 'View your activity or a member\'s activity on LinkedIn',
  author: 'LinkedIn Help',
  url: 'https://www.linkedin.com/help/linkedin/answer/a546122/viewing-recent-activity?lang=en',
});
const LINKEDIN_OPEN_TO_WORK_SOURCE = Object.freeze({
  title: 'Let recruiters know you are Open to Work',
  author: 'LinkedIn Help',
  url: 'https://www.linkedin.com/help/linkedin/answer/a507508/making-your-profile-visible-or-hidden-from-recruiters?lang=en',
});
const HARVARD_RESUME_SOURCE = Object.freeze({
  title: 'Create a Resume or Cover Letter',
  author: 'Harvard FAS Mignone Center for Career Success',
  url: 'https://careerservices.fas.harvard.edu/resources/hes-create-impactful-resumes-and-cover-letters/',
});
const DOL_RESUME_SOURCE = Object.freeze({
  title: 'Resume Essentials Participant Guide',
  author: 'U.S. Department of Labor',
  url: 'https://www.dol.gov/sites/dolgov/files/VETS/files/ResumeEssentials_PG_Interactive_Feb2026.pdf',
});
const CAREER_SEARCH_SOURCE = Object.freeze({
  title: 'Job Search',
  author: 'CareerOneStop, U.S. Department of Labor',
  url: 'https://www.careeronestop.org/JobSearch/job-search.aspx',
});
const DOL_INTERVIEW_SOURCE = Object.freeze({
  title: 'Interview Tips',
  author: 'U.S. Department of Labor',
  url: 'https://www.dol.gov/general/jobs/interview-tips?lang=en',
});
const DOL_INTERVIEW_GUIDE = Object.freeze({
  title: 'Interview Skills Participant Guide',
  author: 'U.S. Department of Labor',
  url: 'https://www.dol.gov/sites/dolgov/files/VETS/files/InterviewSkills_PG_Interactive_Feb2026.pdf',
});

const PILLAR_LABEL = Object.freeze({
  linkedin: 'LINKEDIN',
  resume: 'RESUME',
  search: 'JOB SEARCH',
  application: 'APPLICATION',
  interview: 'INTERVIEW',
});

function guide({
  id, pillar, title, promise, context, action, actionTitle = 'Do this', before, after,
  second, secondTitle = 'A useful adjustment', checklist, cta, sources,
}) {
  return Object.freeze({
    id,
    version: '2',
    pillar,
    title,
    promise,
    slides: Object.freeze([
      Object.freeze({ kind: 'cover', title, body: promise }),
      Object.freeze({ kind: 'context', title: 'Why it matters', body: context }),
      Object.freeze({ kind: 'action', title: actionTitle, body: action }),
      Object.freeze({ kind: 'example', title: 'Before and after', before, after }),
      Object.freeze({ kind: 'action', title: secondTitle, body: second }),
      Object.freeze({ kind: 'checklist', title: 'Quick checklist', items: Object.freeze(checklist) }),
      Object.freeze({ kind: 'cta', title: 'Apply it today', body: cta }),
    ]),
    story: Object.freeze({
      eyebrow: PILLAR_LABEL[pillar],
      title,
      body: `${promise} Read the full guide in the feed.`,
    }),
    caption: Object.freeze({
      hook: promise,
      action: `${cta} Save this guide before your next application.`,
    }),
    hashtags: Object.freeze(['OpeningsDev', 'CareerTips', PILLAR_LABEL[pillar].replaceAll(' ', '')]),
    sources: Object.freeze(sources),
    minRepeatDays: 84,
  });
}

export const EDITORIAL_CATALOG = Object.freeze([
  guide({
    id: 'linkedin-headline-clara', pillar: 'linkedin', title: 'Make your LinkedIn headline say what you do',
    promise: 'Replace a loose keyword list with a clear role, specialty, and outcome.',
    context: 'Your headline appears in search results, comments, and connection requests. It should help a recruiter understand your work in a few seconds.',
    action: 'Use this structure: role or specialty + technology or sector + outcome. Choose terms that appear in target jobs and match your real experience.',
    before: 'Developer | Looking for opportunities',
    after: 'Backend Developer | Node.js and APIs | Reliable payment systems',
    second: 'Skip the long tool list. Two strong keywords and one useful outcome say more than ten disconnected terms.',
    checklist: ['Specific role', 'Two relevant keywords', 'Outcome or sector', 'No empty claims'],
    cta: 'Write one headline, then compare it with three roles you would apply for.', sources: [LINKEDIN_HEADLINE_SOURCE],
  }),
  guide({
    id: 'linkedin-idioma-do-perfil', pillar: 'linkedin', title: 'Match your LinkedIn language to your target market',
    promise: 'Make your profile easy to read without relying on improvised translation.',
    context: 'A profile aimed at international roles should present your work, results, and technical terms in the language used by those employers.',
    action: 'Choose one primary language for your main search. If you target two markets, create a secondary profile and keep facts and dates consistent.',
    before: 'English headline, mixed-language About section and experience',
    after: 'One complete primary profile and a consistent secondary version',
    second: 'Keep official company and product names unchanged. Translate the context, responsibility, and result for the reader.',
    checklist: ['Language matches target jobs', 'Sections stay consistent', 'Technical terms sound natural', 'Dates match in both versions'],
    cta: 'Review five target jobs and note which language dominates the descriptions.', sources: [LINKEDIN_LANGUAGE_SOURCE],
  }),
  guide({
    id: 'linkedin-sobre-que-posiciona', pillar: 'linkedin', title: 'Write an About section with focus and proof',
    promise: 'Connect your experience, strongest skills, and next direction in four short paragraphs.',
    context: 'Your About section should guide the reader, not repeat your full resume. It needs a clear focus and at least one reason to believe you.',
    action: 'Start with your role and focus. Add two strengths, one concrete result, and the kind of problem you want to solve next. Use first person.',
    before: 'Passionate technology professional who loves new challenges.',
    after: 'I build reliable data pipelines. A recent redesign cut payment processing time by 38%.',
    second: 'Use short paragraphs. Add keywords only where they describe work you have done. End with a specific professional direction.',
    checklist: ['Role and focus', 'Two useful strengths', 'One concrete result', 'Clear next direction'],
    cta: 'Draft four short paragraphs and remove every sentence that adds no evidence.', sources: [LINKEDIN_ABOUT_SOURCE],
  }),
  guide({
    id: 'linkedin-titulo-de-experiencia', pillar: 'linkedin', title: 'Use experience titles recruiters can understand',
    promise: 'Clarify an internal title without inventing seniority or hiding your specialty.',
    context: 'Internal job titles can be hard to recognize outside one company. A familiar term improves scanning when it remains faithful to the actual role.',
    action: 'Keep the official title and add a specialty in parentheses when needed. Use the description to explain scope, level, and decisions.',
    before: 'Ninja II',
    after: 'Software Engineer II (Backend)',
    second: 'Do not promote yourself in the title. Show seniority through complexity, ownership, decisions, and results in the experience details.',
    checklist: ['Accurate title', 'Clear specialty', 'Provable seniority', 'Recognizable terms'],
    cta: 'Review every internal title that an external recruiter may not understand.', sources: [LINKEDIN_EXPERIENCE_SOURCE],
  }),
  guide({
    id: 'linkedin-resultados-na-experiencia', pillar: 'linkedin', title: 'Turn LinkedIn duties into outcomes',
    promise: 'Show how your work changed a product, process, cost, risk, or customer result.',
    context: 'A duty list describes what the role required. Outcomes show what you delivered and give the reader a reason to trust your experience.',
    action: 'Write each point as action + context + result. If revenue is not relevant, use scale, time, adoption, quality, or risk.',
    before: 'Responsible for building APIs and fixing bugs.',
    after: 'Redesigned 6 critical APIs and cut integration failures by 31% in four months.',
    second: 'Use a specific verb and explain what the number compares. An honest estimate with context is better than a large number with no basis.',
    checklist: ['Specific action', 'Defined scope', 'Observed result', 'Metric with context'],
    cta: 'Rewrite the first point in your most recent experience today.', sources: [LINKEDIN_EXPERIENCE_SOURCE],
  }),
  guide({
    id: 'linkedin-skills-encontraveis', pillar: 'linkedin', title: 'Make your LinkedIn skills match your target role',
    promise: 'Keep a focused skill list that reflects both your target jobs and your real work.',
    context: 'A generic skill list weakens your positioning. Your main skills should match the work you want and the evidence already on your profile.',
    action: 'Collect repeated terms from ten realistic jobs. Keep only skills you can discuss, then connect important skills to related experience.',
    before: 'A long mix of Office, leadership, Java, design, and marketing',
    after: 'A focused set of backend, API, database, and cloud skills',
    second: 'Order skills by relevance to your target role, not by the date you added them. Remove stale or unrelated items.',
    checklist: ['Terms from target jobs', 'Skills you can prove', 'Links to real experience', 'Current priorities first'],
    cta: 'Compare your first ten skills with the requirements in three target jobs.', sources: [LINKEDIN_SKILLS_SOURCE],
  }),
  guide({
    id: 'linkedin-provas-em-destaque', pillar: 'linkedin', title: 'Use Featured to show proof, not clutter',
    promise: 'Point recruiters to work samples that support the claims on your profile.',
    context: 'Saying you can do the work is different from showing it. A focused Featured section shortens the path from claim to evidence.',
    action: 'Choose two to four items tied to your target role: a case study, explained repository, article, talk, demo, or portfolio.',
    before: 'Old links with no title or explanation',
    after: 'Case study: cloud migration cut monthly cost by 24%, with context and decisions',
    second: 'Give each item a title that explains its value. Remove broken, confidential, unclear, or unrelated material.',
    checklist: ['Relevant proof', 'Useful title', 'Working link', 'No confidential data'],
    cta: 'Choose one real work sample and write one line explaining why it matters.', sources: [LINKEDIN_FEATURED_SOURCE],
  }),
  guide({
    id: 'linkedin-recomendacoes-que-comprovam', pillar: 'linkedin', title: 'Ask for recommendations with useful context',
    promise: 'Help a former colleague describe your work with more than a generic compliment.',
    context: 'A useful recommendation explains the working relationship, a real situation, and your contribution. Praise alone adds little evidence.',
    action: 'Ask someone who saw your work closely. Mention the project, your responsibility, and the result so the request is easy to answer.',
    before: 'Could you write me a recommendation?',
    after: 'Could you mention our migration, my role in the decision, and the effect on the team?',
    second: 'Seek different viewpoints from a manager, peer, or partner team. Do not write the final recommendation for them.',
    checklist: ['Real working relationship', 'Specific project', 'Clear contribution', 'Different viewpoints'],
    cta: 'Choose one person and send a short request with enough context.', sources: [LINKEDIN_RECOMMENDATIONS_SOURCE],
  }),
  guide({
    id: 'linkedin-contexto-remoto', pillar: 'linkedin', title: 'Show how you work with remote teams',
    promise: 'Prove distributed collaboration instead of adding the word remote to your profile.',
    context: 'Remote work depends on communication, ownership, and coordination across schedules. Those skills are stronger when tied to real situations.',
    action: 'Mention distributed teams, time zones, async routines, documentation, and how your approach reduced delays or confusion.',
    before: 'Experienced in remote work.',
    after: 'Coordinated async releases across Brazil and Europe, cutting delivery blockers by 20%.',
    second: 'State your location and work preference clearly. Do not promise hours or time-zone coverage you cannot sustain.',
    checklist: ['Distributed team context', 'Communication practice', 'Observed result', 'Realistic availability'],
    cta: 'Add one proof of remote collaboration to the most relevant experience.', sources: [LINKEDIN_PROFILE_SOURCE],
  }),
  guide({
    id: 'linkedin-contato-profissional', pillar: 'linkedin', title: 'Make it easy to contact you',
    promise: 'Give a recruiter one clear professional path to start a conversation.',
    context: 'A strong profile still loses opportunities when contact details are hidden, stale, or broken. Privacy remains part of the decision.',
    action: 'Review your professional email, portfolio, location, and profile URL. Share only the details needed for an initial conversation.',
    before: 'Old email and a broken portfolio link',
    after: 'Current email, clean profile URL, and a working portfolio',
    second: 'Test every link in a private window. Keep your home address, personal documents, and unnecessary phone details private.',
    checklist: ['Current email', 'Clean profile URL', 'Tested portfolio', 'Privacy reviewed'],
    cta: 'View your profile as a visitor and test every contact path.', sources: [LINKEDIN_CONTACT_SOURCE],
  }),
  guide({
    id: 'linkedin-atividade-estrategica', pillar: 'linkedin', title: 'Make your LinkedIn activity support your profile',
    promise: 'Use posts and comments to show how you think about the work you want.',
    context: 'Your activity is part of your professional impression. Useful participation can show judgment, clarity, and genuine interest in the field.',
    action: 'Comment with a relevant example, data point, or question. When you post, explain the context, decision, and result.',
    before: 'Great post. Thanks for sharing!',
    after: 'We saw this trade-off in checkout. Measuring errors by step changed our priority.',
    second: 'Choose consistency over volume. Two useful contributions a week say more than generic comments on dozens of posts.',
    checklist: ['Relevant topic', 'Concrete contribution', 'Professional tone', 'Sustainable pace'],
    cta: 'Write one comment today that adds an example, question, or useful counterpoint.', sources: [LINKEDIN_ACTIVITY_SOURCE],
  }),
  guide({
    id: 'linkedin-privacidade-open-to-work', pillar: 'linkedin', title: 'Use Open to Work with the right privacy setting',
    promise: 'Signal what you want with role, location, work model, and visibility choices.',
    context: 'Specific preferences help recruiters assess fit. Your visibility setting should also match your current employment and privacy needs.',
    action: 'Set realistic roles, locations, work models, and start dates. Choose whether all members or recruiters only can see the signal.',
    before: 'Open to any opportunity, anywhere',
    after: 'Backend Engineer, remote in Brazil or hybrid in Sao Paulo, available in 30 days',
    second: 'Review the settings when your search changes. A platform signal does not replace a focused search and direct applications.',
    checklist: ['Defined roles', 'Realistic locations', 'Preferred work model', 'Intentional visibility'],
    cta: 'Open your preferences and remove any option you would not actually accept.', sources: [LINKEDIN_OPEN_TO_WORK_SOURCE],
  }),

  guide({
    id: 'resume-resumo-direto', pillar: 'resume', title: 'Write a resume summary that earns the next 10 seconds',
    promise: 'State your role, specialty, and strongest evidence in three or four lines.',
    context: 'The top of your resume should guide the first scan. A generic objective takes space without showing why you fit the role.',
    action: 'Use three parts: professional identity, core strengths, and one relevant result. Adjust the emphasis for each target job.',
    before: 'Seeking an opportunity to grow and contribute to the company.',
    after: 'Product Designer with 5 years in B2B SaaS. A recent onboarding redesign raised activation by 18%.',
    second: 'Remove adjectives you cannot prove. Early in your career, use a relevant project, technical skill, and context instead of years.',
    checklist: ['Target role', 'Clear specialty', 'Concrete evidence', 'Four lines or fewer'],
    cta: 'Delete the sentence that could describe any candidate and replace it with your proof.', sources: [HARVARD_RESUME_SOURCE, DOL_RESUME_SOURCE],
  }),
  guide({
    id: 'resume-bullets-de-impacto', pillar: 'resume', title: 'Turn resume duties into impact bullets',
    promise: 'Give each bullet one clear action, context, and result.',
    context: 'Responsibilities describe the job. Accomplishments distinguish the candidate. Each bullet should make one contribution easy to scan.',
    action: 'Start with a specific verb, explain what changed, and end with a result or scale. Keep one main idea in each bullet.',
    before: 'Responsible for system testing.',
    after: 'Automated 140 critical tests and cut production regressions by 27%.',
    second: 'Order bullets by relevance to the target role, not by task chronology. Keep three to five strong points for each recent job.',
    checklist: ['Specific verb', 'One idea per bullet', 'Result or scale', 'Relevant points first'],
    cta: 'Rewrite the most generic bullet in your latest role.', sources: [HARVARD_RESUME_SOURCE, DOL_RESUME_SOURCE],
  }),
  guide({
    id: 'resume-metricas-com-contexto', pillar: 'resume', title: 'Use metrics people can trust',
    promise: 'Give your work scale with honest numbers and a clear basis for comparison.',
    context: 'Metrics help a reader judge scale and effect. Without context, a number can look decorative or difficult to trust.',
    action: 'Look for volume, time, adoption, quality, cost, revenue, or risk. State the period, baseline, or group being measured.',
    before: 'Improved application performance significantly.',
    after: 'Cut p95 latency from 1.8 seconds to 900 ms on three routes used by 60,000 customers.',
    second: 'If exact data is confidential, use a percentage, range, or approximate scale without exposing protected information.',
    checklist: ['Defensible metric', 'Comparison point', 'Period or scale', 'No confidential data'],
    cta: 'List three results and pair each one with a number you can explain.', sources: [HARVARD_RESUME_SOURCE, DOL_RESUME_SOURCE],
  }),
  guide({
    id: 'resume-formato-ats', pillar: 'resume', title: 'Build a resume an ATS can parse',
    promise: 'Use a simple structure so important information stays readable to people and systems.',
    context: 'Complex layouts can disrupt scanning and data extraction. Clear hierarchy also helps a recruiter review the file quickly.',
    action: 'Use one column, familiar section names, reverse chronological order, and selectable text. Format roles and dates consistently.',
    before: 'Two columns, skill bars, icons, and key details placed inside images',
    after: 'Clear sections, real text, simple hierarchy, and consistent dates',
    second: 'Export as PDF when requested, then copy the text into a plain editor. The reading order should still make sense.',
    checklist: ['One column', 'Familiar section names', 'Selectable text', 'Requested file type'],
    cta: 'Copy your PDF into a plain editor and check the reading order.', sources: [HARVARD_RESUME_SOURCE, DOL_RESUME_SOURCE],
  }),
  guide({
    id: 'resume-curriculo-por-vaga', pillar: 'resume', title: 'Tailor your resume without rewriting everything',
    promise: 'Change the emphasis and order so the strongest evidence appears first.',
    context: 'One generic resume often highlights the wrong details. Tailoring means selecting relevant proof, not changing your history.',
    action: 'Mark required and preferred qualifications. Reorder your summary, skills, and bullets so matching evidence appears early.',
    before: 'The same resume sent to frontend, data, and management roles',
    after: 'A version that puts role-specific experience and evidence first',
    second: 'Use job-post language only when it describes work you have done. Do not paste requirements or add a skill you cannot prove.',
    checklist: ['Requirements marked', 'Summary adjusted', 'Evidence moved up', 'No inflated claims'],
    cta: 'Choose the three requirements your resume must prove before the next application.', sources: [HARVARD_RESUME_SOURCE, DOL_RESUME_SOURCE],
  }),
  guide({
    id: 'resume-projetos-relevantes', pillar: 'resume', title: 'Add projects that prove relevant skills',
    promise: 'Give personal, academic, or volunteer work a clear problem, role, and result.',
    context: 'Projects can close an experience gap when they show decisions and skills that resemble the target work.',
    action: 'Describe the problem, your role, key choices, and result. If a team was involved, make your individual contribution clear.',
    before: 'Built an ecommerce project in React.',
    after: 'Built an accessible React checkout, tested it with 8 users, and fixed 12 navigation barriers.',
    second: 'Choose a few strong projects. A link only helps when it works, explains setup, and exposes no secrets.',
    checklist: ['Defined problem', 'Individual role', 'Explained decisions', 'Result or lesson'],
    cta: 'Pick the project closest to your target role and rewrite it as three bullets.', sources: [HARVARD_RESUME_SOURCE, DOL_RESUME_SOURCE],
  }),
  guide({
    id: 'resume-portfolio-que-prova', pillar: 'resume', title: 'Make your portfolio answer recruiter questions',
    promise: 'Turn each link into clear evidence of your role, decisions, and result.',
    context: 'A portfolio with no context makes the recruiter reconstruct the work. Each case should explain the problem and your contribution.',
    action: 'For each case, show the setting, constraints, options, your decision, and the result. Protect confidential material.',
    before: 'A gallery of screens with no explanation',
    after: 'A case with the problem, options considered, decision, and measured effect',
    second: 'Use stable URLs and descriptive titles. Test each case on mobile and in a private window.',
    checklist: ['Problem has context', 'Your role is explicit', 'Decision is visible', 'Public link works'],
    cta: 'Open your main case as a visitor and note what is unclear after 30 seconds.', sources: [HARVARD_RESUME_SOURCE],
  }),
  guide({
    id: 'resume-revisao-final', pillar: 'resume', title: 'Run a final resume check before you apply',
    promise: 'Check the content, consistency, links, and file before you submit.',
    context: 'Small errors can raise questions about attention to detail. A short routine reduces risk without delaying the application.',
    action: 'Read the resume outside the editor and once aloud. Compare the role, company, and core requirements with the job post again.',
    before: 'resume_final_really-v3.pdf with a broken link and mismatched dates',
    after: 'first-last-role.pdf with consistent dates and tested links',
    second: 'Ask someone to name your strongest qualification after one scan. If the answer is unclear, fix the order and emphasis.',
    checklist: ['Spelling checked', 'Dates consistent', 'Links tested', 'Clear file name'],
    cta: 'Create one fixed checklist and complete all four checks before submitting.', sources: [HARVARD_RESUME_SOURCE, DOL_RESUME_SOURCE],
  }),

  guide({
    id: 'search-busca-com-criterios', pillar: 'search', title: 'Define your search before opening a job board',
    promise: 'Focus on roles you would seriously consider instead of applying to anything nearby.',
    context: 'A search without criteria creates volume but weak decisions. Clear limits help you compare roles and spend time on stronger applications.',
    action: 'Define role, level, pay floor, location, work model, sectors, and constraints. Separate requirements from preferences.',
    before: 'Apply to any job related to technology.',
    after: 'Mid-level backend, remote in Brazil, B2B product, with a defined pay floor',
    second: 'Review the criteria against real openings every two weeks. Adjust expectations without ignoring important needs.',
    checklist: ['Target role', 'Pay floor', 'Location and work model', 'Clear constraints'],
    cta: 'Write your four non-negotiable criteria before the next search.', sources: [CAREER_SEARCH_SOURCE],
  }),
  guide({
    id: 'search-alertas-uteis', pillar: 'search', title: 'Set job alerts that filter noise',
    promise: 'Receive roles closer to your target and review them before the list grows stale.',
    context: 'A broad alert fills your inbox and hides better matches. Smaller combinations produce a cleaner signal.',
    action: 'Create separate alerts by title, level, and location. Add real title variants and exclude recurring false positives when possible.',
    before: 'One alert for developer',
    after: 'Separate alerts for backend engineer, Node.js developer, and API engineer in Brazil',
    second: 'Set two short review windows each day. Disable any alert that produces no realistic matches after one week.',
    checklist: ['Specific title', 'Useful title variants', 'Defined location', 'Weekly cleanup'],
    cta: 'Split your broadest alert into two focused searches.', sources: [CAREER_SEARCH_SOURCE],
  }),
  guide({
    id: 'search-fontes-alem-do-linkedin', pillar: 'search', title: 'Look beyond one job board',
    promise: 'Broaden your coverage without turning the search into endless browsing.',
    context: 'Companies publish through different channels. Some openings appear first on company career pages or in specialist communities.',
    action: 'Use a short source list: one aggregator, target company pages, relevant communities, and your professional network.',
    before: 'Refresh the same job feed several times a day.',
    after: 'Check one aggregator, 15 target companies, and two relevant communities',
    second: 'Record where each opening came from. After four weeks, keep the sources that produce realistic roles or useful conversations.',
    checklist: ['Trusted aggregator', 'Target companies', 'Relevant communities', 'Source recorded'],
    cta: 'Choose five companies today and save each career page.', sources: [CAREER_SEARCH_SOURCE],
  }),
  guide({
    id: 'search-pesquisa-de-empresa', pillar: 'search', title: 'Research a company before you apply',
    promise: 'Find the context, risks, and specific reasons behind your interest.',
    context: 'A job post does not show the full work environment. Basic research improves your resume, message, interview, and decision.',
    action: 'Check the product, customers, business model, recent news, leadership, published values, and people in the function. Compare sources.',
    before: 'The company looks interesting and uses a tool I like.',
    after: 'I understand the product, business stage, and two likely team challenges.',
    second: 'Separate facts, opinions, and your own hypotheses. Anonymous reviews are one signal, not the whole decision.',
    checklist: ['Product understood', 'Business stage checked', 'Relevant team found', 'Risks noted'],
    cta: 'Write two specific reasons to speak with the company before applying.', sources: [CAREER_SEARCH_SOURCE],
  }),
  guide({
    id: 'search-networking-intencional', pillar: 'search', title: 'Network with a clear reason',
    promise: 'Start a useful professional conversation without asking for a job in the first line.',
    context: 'Networking works best as an exchange of information and perspective. A vague request pushes all the effort onto the other person.',
    action: 'Start from a specific interest: published work, sector experience, or a career decision. Ask one short, researched question.',
    before: 'Hi, do you have any jobs? Can you refer me?',
    after: 'I saw your move into data. Which skill mattered most when you joined that team?',
    second: 'Respect their time and do not chase a reply. Share something useful when relevant, and keep the relationship beyond one immediate need.',
    checklist: ['Specific context', 'Short question', 'No pressure', 'Room for reciprocity'],
    cta: 'Choose one person in your field and draft a message with real context.', sources: [CAREER_SEARCH_SOURCE],
  }),
  guide({
    id: 'search-rotina-semanal', pillar: 'search', title: 'Build a weekly job search routine',
    promise: 'Replace anxious scrolling with a small process you can measure and repeat.',
    context: 'A job search includes discovery, research, tailoring, conversations, and follow-up. Mixing every step makes progress hard to see.',
    action: 'Schedule separate blocks to find, select, tailor, contact, and follow up. Set quality goals, not only application volume.',
    before: 'Scroll for hours and apply whenever there is time.',
    after: 'Three 45-minute blocks, four strong applications, and two conversations a week',
    second: 'Track the date, role, resume version, contact, and next step. Review the funnel to find where your process needs attention.',
    checklist: ['Calendar blocks', 'Quality target', 'Follow-up recorded', 'Weekly review'],
    cta: 'Schedule three short search blocks for next week now.', sources: [CAREER_SEARCH_SOURCE],
  }),

  guide({
    id: 'application-leia-os-requisitos', pillar: 'application', title: 'Read job requirements by evidence, not intimidation',
    promise: 'Separate true requirements from preferences before deciding you are not a fit.',
    context: 'Job descriptions mix responsibilities, required qualifications, and preferences. Treating every line as a hard filter removes viable roles.',
    action: 'Mark each item as required, preferred, or context. Add one proof for each requirement and assess the real effect of any gap.',
    before: 'I do not match every item, so I will not apply.',
    after: 'I meet the core requirements and can explain two preferred-skill gaps.',
    second: 'Do not ignore legal eligibility, required language, or essential availability. Use judgment, not a magic percentage.',
    checklist: ['Requirements separated', 'Preferences separated', 'Evidence noted', 'Gaps assessed'],
    cta: 'Take one saved role and sort its qualifications into three groups.', sources: [DOL_RESUME_SOURCE, CAREER_SEARCH_SOURCE],
  }),
  guide({
    id: 'application-evidencias-de-fit', pillar: 'application', title: 'Show evidence of fit in every application',
    promise: 'Connect each important requirement to proof from your work, study, or projects.',
    context: 'An application is stronger when the resume and answers make the match explicit. Do not force the reader to infer your fit.',
    action: 'Create two columns: requirement and evidence. Use a real project, result, decision, or lesson, then move the best proof into the resume.',
    before: 'I am a strong fit for this role.',
    after: 'Requirement: APIs. Evidence: redesigned 6 APIs and cut failures by 31%.',
    second: 'If you have no proof, do not invent it. Use transferable experience, build a relevant project, or state the gap honestly.',
    checklist: ['Priority requirements', 'One proof for each', 'Metric when useful', 'Honest gaps'],
    cta: 'Build the table for the five most important requirements in your next role.', sources: [DOL_RESUME_SOURCE],
  }),
  guide({
    id: 'application-respostas-concisas', pillar: 'application', title: 'Answer application questions with tight examples',
    promise: 'Give the reader context, your action, and the result without a long introduction.',
    context: 'Open questions test communication and fit. Long answers can hide the evidence, while vague answers give nothing to assess.',
    action: 'Answer the question in the first sentence. Then add one example with the situation, your action, and the result.',
    before: 'I have always loved challenges and believe I can contribute a lot.',
    after: 'I led a checkout fix in 48 hours. The recovery cut abandonment by 9%.',
    second: 'Review every reused answer. Check the limit, language, and whether each sentence proves something the question asks.',
    checklist: ['Question answered', 'Specific example', 'Your action is clear', 'Result is clear'],
    cta: 'Move the strongest evidence into the first half of your latest answer.', sources: [DOL_RESUME_SOURCE],
  }),
  guide({
    id: 'application-follow-up-profissional', pillar: 'application', title: 'Follow up once, with context',
    promise: 'Restate your interest in a short message that is easy to place and answer.',
    context: 'A follow-up can help restart a conversation. Repeated messages or a note with no context usually create noise.',
    action: 'Wait for the stated timeline. If none exists, wait a few business days. Name the role, date, specific interest, and your availability.',
    before: 'Hi, any news? I need an answer urgently.',
    after: 'I applied for Backend Engineer on Sep 2. The distributed API work stood out, and I remain available.',
    second: 'Send one message through the appropriate channel. If there is no reply, keep pursuing other roles instead of pressing repeatedly.',
    checklist: ['Timeline respected', 'Role identified', 'Specific interest', 'No pressure'],
    cta: 'Draft a four-line template and personalize the reason for your interest.', sources: [CAREER_SEARCH_SOURCE],
  }),

  guide({
    id: 'interview-prepare-historias', pillar: 'interview', title: 'Prepare histórias antes da entrevista',
    promise: 'Chegue com exemplos reais para competências que a vaga deve avaliar.',
    context: 'Sob pressão, é fácil lembrar apenas de tarefas. Um banco de histórias ajuda a responder com contexto, decisões e resultados.',
    action: 'Liste seis situações: entrega difícil, conflito, erro, liderança, aprendizado e resultado. Para cada uma, registre seu papel e o que mudou.',
    before: 'Acho que já trabalhei com algo parecido, mas não lembro os detalhes.',
    after: 'Tenho uma história curta com situação, decisão, resultado e aprendizado.',
    second: 'Use histórias diferentes e verdadeiras. Adapte o foco à pergunta sem decorar um discurso rígido.',
    checklist: ['Seis situações', 'Seu papel explícito', 'Resultado lembrado', 'Aprendizado honesto'],
    cta: 'Escreva agora o título de seis histórias e escolha duas para ensaiar.', sources: [DOL_INTERVIEW_SOURCE, DOL_INTERVIEW_GUIDE],
  }),
  guide({
    id: 'interview-metodo-star', pillar: 'interview', title: 'Use STAR sem parecer que decorou a resposta',
    promise: 'Organize exemplos para responder com começo, ação e resultado.',
    context: 'STAR evita histórias confusas: situação, tarefa, ação e resultado. O maior espaço deve ficar naquilo que você fez e decidiu.',
    action: 'Resuma situação e tarefa em poucas frases. Detalhe sua ação em primeira pessoa e termine com resultado, feedback ou aprendizado.',
    before: 'O time teve um problema e no fim deu tudo certo.',
    after: 'Com 48 horas, priorizei duas falhas, coordenei rollback e reduzi o impacto a 12 minutos.',
    second: 'Não force resultado positivo. Em perguntas sobre erro, explique consequência, correção e o que mudou no seu processo.',
    checklist: ['Situação breve', 'Tarefa clara', 'Ação em primeira pessoa', 'Resultado ou aprendizado'],
    cta: 'Grave uma resposta de dois minutos e veja se a maior parte descreve sua ação.', sources: [DOL_INTERVIEW_SOURCE, DOL_INTERVIEW_GUIDE],
  }),
  guide({
    id: 'interview-comunique-raciocinio', pillar: 'interview', title: 'Mostre seu raciocínio quando não souber a resposta',
    promise: 'Transforme incerteza em uma demonstração de análise e colaboração.',
    context: 'Entrevistas avaliam como você estrutura problemas, não apenas memória. Inventar certeza costuma ser pior que explicitar hipóteses.',
    action: 'Confirme o objetivo, faça perguntas, declare suposições e avance em etapas. Compare opções e diga o que validaria primeiro.',
    before: 'Não sei. Ou talvez seja a opção A.',
    after: 'Não usei isso diretamente; eu começaria validando volume e consistência, depois compararia A e B.',
    second: 'Quando chegar ao limite, diga o que falta para concluir. Convide o entrevistador a esclarecer sem transferir todo o problema.',
    checklist: ['Objetivo confirmado', 'Hipóteses explícitas', 'Opções comparadas', 'Próximo teste definido'],
    cta: 'Pratique explicar um problema técnico em voz alta sem abrir o editor.', sources: [DOL_INTERVIEW_GUIDE],
  }),
  guide({
    id: 'interview-perguntas-ao-entrevistador', pillar: 'interview', title: 'Prepare perguntas que também avaliam a empresa',
    promise: 'Use o final da entrevista para entender trabalho, expectativas e ambiente.',
    context: 'A entrevista é uma conversa de avaliação mútua. Perguntas pesquisadas mostram preparo e ajudam você a decidir com mais informação.',
    action: 'Pergunte sobre sucesso nos primeiros meses, desafios atuais, decisões, colaboração e feedback. Adapte ao papel de quem entrevista.',
    before: 'Não tenho perguntas. Está tudo claro.',
    after: 'Qual problema faria vocês dizerem em seis meses que essa contratação deu certo?',
    second: 'Evite perguntar algo respondido facilmente no site. Salário e condições importam, mas escolha o momento adequado no processo.',
    checklist: ['Sucesso no cargo', 'Desafio real', 'Forma de colaboração', 'Próximos passos'],
    cta: 'Prepare cinco perguntas e marque quais servem para recrutador, liderança e pares.', sources: [DOL_INTERVIEW_SOURCE, DOL_INTERVIEW_GUIDE],
  }),
  guide({
    id: 'interview-entrevista-remota', pillar: 'interview', title: 'Prepare a entrevista remota além da câmera',
    promise: 'Reduza imprevistos e preserve energia para a conversa.',
    context: 'Problemas de áudio, conexão e ambiente afetam comunicação. Um teste simples evita começar a entrevista resolvendo logística.',
    action: 'Teste link, câmera, microfone, energia e conexão. Feche notificações, abra currículo e vaga e tenha um plano alternativo de contato.',
    before: 'Descobrir na hora que o navegador não tem acesso ao microfone.',
    after: 'Teste concluído, ambiente silencioso e telefone de backup disponível.',
    second: 'Olhe para a câmera em momentos-chave, mas não force contato constante. Avise cedo se surgir uma falha e proponha alternativa.',
    checklist: ['Link testado', 'Áudio confirmado', 'Notificações fechadas', 'Plano de backup'],
    cta: 'Faça um teste completo no mesmo dispositivo e ambiente da entrevista.', sources: [DOL_INTERVIEW_GUIDE],
  }),
  guide({
    id: 'interview-revisao-pos-entrevista', pillar: 'interview', title: 'Use o pós-entrevista para melhorar a próxima',
    promise: 'Registre sinais, dúvidas e aprendizados enquanto a conversa está fresca.',
    context: 'Sem revisão, detalhes desaparecem e os mesmos pontos fracos se repetem. O registro também ajuda a comparar oportunidades.',
    action: 'Anote perguntas, respostas fortes, pontos confusos, informações da empresa e próximos passos. Envie agradecimento curto se for adequado.',
    before: 'Acho que foi bem; agora é esperar.',
    after: 'Registrei 8 perguntas, 2 respostas para melhorar e o prazo combinado.',
    second: 'Não transforme cada silêncio em conclusão. Use apenas sinais observáveis e continue seu processo de busca enquanto aguarda.',
    checklist: ['Perguntas registradas', 'Respostas revisadas', 'Prazo anotado', 'Próxima melhoria definida'],
    cta: 'Crie uma nota padrão e preencha nos primeiros 15 minutos após cada entrevista.', sources: [DOL_INTERVIEW_SOURCE, DOL_INTERVIEW_GUIDE],
  }),
]);
